### PR TITLE
Vanilla 1.7.0 mobile headings demo

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
# DON'T MERGE

This is a demo of mobile headings on ubuntu.com using the values from https://github.com/vanilla-framework/vanilla-framework/pull/1796

| Heading | Large-screen | Small-screen |
|---------|----------|--------|
| h1      | 8        | 6      |
| h2      | 6        | 4.5      |
| h3      | 4        | 3      |
| h4      | 2        | 1.5      |
| h5      | 1        | 1      |
| h6      | 1        | 1      |

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
@Caleb-Ellis overall new mobile heading sizes looking good, only noticed a couple of minor bugs which should be a quick fix 👍 

- /containers/overview and /containers/lxd and /containers/docker-ubuntu seems to be an issue with paddings between headings
screen shot 2018-05-04 at 11 47 17
screen shot 2018-05-04 at 11 47 30
screen shot 2018-05-04 at 11 47 41

- also on stepped-lists the numerical order icons have transformed from round to oval 🏉 
screen shot 2018-05-04 at 11 43 02

@spencerbygraves have you had a chance to have a look?

**Comment by spencerbygraves** [comment]
@kwm14 @Caleb-Ellis yes, the sizes look ok. As you said, there's some spacing issues.

image

**Comment by Caleb-Ellis** [comment]
@kwm14 @spencerbygraves ready for another look at

The main issues were bespoke styling and incorrect markup on u.com, and I'd forgotten to take into account the interactions between `<p>` elements that immediately follow the new mobile headings. Anyway it should be all fixed now, and changes have been made upstream at https://github.com/vanilla-framework/vanilla-framework/pull/1796

**Comment by kwm14** [comment]
@Caleb-Ellis design updates looking good from myself and @spencerbygraves 👍 💯

**Comment by Caleb-Ellis** [comment]
Closing and proposing https://github.com/vanilla-framework/vanilla-framework/pull/1796 to be included in Vanilla

**Pull request closed without merging**
