### PR TITLE
2905 remove snappy page

### LINKED ISSUE #2905: /desktop/snappy remove and add redirect to /desktop/developer

### PR DESCRIPTION
**Pull request by steverydz**
## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/desktop/snappy>
- Check that page is redirected to `/desktop/developers`

## Issue / Card

Fixes #2905

### CODE REVIEW

**Comment by Caleb-Ellis** [comment]
@steverydz I think we should separate out the legal page stuff and removing snappy page stuff in to separate PRs that are named accordingly. Unless this is another instance of phantom commits :confused:

**Comment by steverydz** [comment]
@Caleb-Ellis I'll fix it. Definitely wasn't intentional!

**Comment by steverydz** [comment]
New PR at https://github.com/canonical-websites/www.ubuntu.com/pull/2919

**Comment by frankiegranato** [comment]
@steverydz  Have we already removed the /snappy page? If so, can you be sure to add a redirect to /desktop/developer as noted in the copydoc: https://docs.google.com/document/d/19EIGiQ4FLfWVQczBgAqj5lIcWGnM0GmVGWggFIXcHt0/edit# please?                       
Sorry if this is annoying :-)

**Pull request closed without merging**
