### PR TITLE
Update, move webinar embed

### PR DESCRIPTION
**Pull request by Khutch25**
## Done

Moved the BrightTALK webinar embed from the bottom to the top and replaced it with the German version of the webinar for this page.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by Caleb-Ellis** [comment]
Nice, @Khutch25! Happy to merge as-is, but did you want to move the webinar on the English version too?

**Comment by anasereijo** [comment]
Hi,

Just a couple of things and it's ready to go:

- Please make the copy card (hero section) `col-7` - that way the word Canonical will sit next to OpenStack (can we do that on the English version too?)

- The video section is looking quite small at the moment. Can we match with the English version? (see below)
screen shot 2018-08-21 at 11 00 58

thank you

**Comment by Khutch25** [comment]
Just submitted a pull request for the col-7 update. For the video,
unfortunately, this is a BrightTALK issue. Since this is a live webinar,
their design embed defaults to a smaller size as opposed to the on-demand
(finished) webinar size that you see on the English page. Once this webinar
is in the post-live phase, I will submit a pull request for the updated
size embed.

Thank you!

**Comment by anasereijo** [comment]
hey @Khutch25 as discussed can you please make the hero text `col-6` on German version and  `col-7` on the English version.

Thank you!

**Pull request merged**
