### PR TITLE
update /download/server/linuxone to vbt

### LINKED ISSUE #1642: /download/server/linuxone/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /download/server/linuxone to vbt
* moved the t&c to under the button

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/server/linuxone)
* compare to the [design](https://www.dropbox.com/s/few9kkpkqlwz52a/download-server-linuxone.png?dl=0) and [demo](http://www.ubuntu.com-1642-download-server-linuxone.demo.haus/download/server/linuxone)

## Issue / Card

Fixes #1642

### CODE REVIEW

**Comment by yaili** [comment]
- [ ] Remove the double contextual footer border (remove dotted border)

**Comment by deadlight** [comment]
Code looks good but I'll wait for you to address the design QA issue before doing the final check.

@pmahnke - Can you update the design link to point to the correct design, please?

**Comment by yaili** [comment]
@deadlight I've updated the design link now

**Comment by pmahnke** [comment]
@yaili fixed @deadlight too

**Pull request merged**
