### PR TITLE
update /index_kylin to vbt

### LINKED ISSUE #1578: /index_kylin to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /index_kylin to vbt
* added a breadcrumb as well

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/index_kylin)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/1.%20Home?preview=homepage-china.png)

## Issue / Card

Fixes #1578

### CODE REVIEW

**Comment by yaili** [comment]
Just a reminder that this demo isn't working.

**Comment by deadlight** [comment]
@pmahnke I'm getting very odd styling on the homepage:

homepage

**Comment by pmahnke** [comment]
@deadlight I created a base_index-v1 to stop this... I thought the homepage didn't use that... but I missed that it did.

**Comment by barrymcgee** [comment]
@yaili Workign demo: http://www.ubuntu.com-kylin-demo.demo.haus/index_kylin

FYI @pmahnke - using underscores or other special characters in branch names breaks the demo.

**Comment by yaili** [comment]
Design review:
- [ ] Should we remove the breadcrumb on this page?
- [ ] Can we hide the image in S screen?

**Comment by pmahnke** [comment]
@yaili fixed
@barrymcgee can you repull into your branch and rebuild the demo

**Comment by barrymcgee** [comment]
Rebuilt demo: http://www.ubuntu.com-kylin-demo.demo.haus/index_kylin

**Pull request merged**
