### PR TITLE
update /core/contact-us to vbt

### LINKED ISSUE #1599: /core/contact-us/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* updated /core/contact-us to VBT

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/core/contact-us)
- [demo](http://www.ubuntu.com-1599-core-contact-us.demo.haus/core/contact-us)

## Issue / Card

Fixes #1599

### CODE REVIEW

**Comment by yaili** [comment]
- [ ] There is a double border in the breadcrumbs at S screen because there is only one item

screen shot 2017-05-25 at 08 58 03

**Comment by pmahnke** [comment]
@yaili I had fixed in contact us... but moved it here

**Comment by yaili** [comment]
Seeing the same double border in S screen breadcrumbs bug

**Comment by pmahnke** [comment]
@yaili fixed in both demos

**Comment by yaili** [comment]
The Overview row in the S screen breadcrumbs is taller than the Core row, it should be the same height if both only have one item. There is also a couple of pixels gap between the breadcrumb and the left edge of the viewport but I've seen this fixed in about demos. Has this been fixed somewhere else, or should I file a separate bug to fix the height and/or gap?

**Comment by pmahnke** [comment]
@yaili I assume this is what @deadlight and @grahambancroft are working on...

**Comment by yaili** [comment]
@deadlight @grahambancroft can you confirm before I +1 this?

**Comment by yaili** [comment]
- [ ] The chevron here is really bold and looks different - is there another demo link I can compare with that has a more final version of it? I'm confused as to which demos have the correct things

**Comment by pmahnke** [comment]
@yaili I think @barrymcgee fixed the chevron over my fix of the chevron... so it was there twice!

**Pull request merged**
