### PR TITLE
Update screenshot image

### LINKED ISSUE #2974: Update /cloud/public-cloud - Build
please update the photo of the laptop

link: https://assets.ubuntu.com/v1/79439f53-Dell_XPS_Laptop_Front-Developer.png

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Replace laptop image on `/cloud/public-cloud`

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/cloud/public-cloud>
- Check that laptop image is [same as this](https://assets.ubuntu.com/v1/79439f53-Dell_XPS_Laptop_Front-Developer.png)

## Issue / Card

Fixes #2974

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz the image looks a bit blurred. anyway we can fix this? thanks

**Comment by steverydz** [comment]
@anasereijo What I see in browser looks the same as the source image to me? https://assets.ubuntu.com/v1/79439f53-Dell_XPS_Laptop_Front-Developer.png?w=540

**Comment by anasereijo** [comment]
@steverydz I think that link is a resized image. if you take the ?w=540 from url looks better
https://assets.ubuntu.com/v1/79439f53-Dell_XPS_Laptop_Front-Developer.png

**Comment by frankiegranato** [comment]
I've added my +1 but the important thing is that @anasereijo is happy with the image :-)

**Comment by steverydz** [comment]
@anasereijo Ah, it's probably because you have a retina screen. Yes it's resized to the size it's displayed at. We can't load 2000+ px  image for something that small, but I can load a slightly larger one and compress it in browser.

**Comment by steverydz** [comment]
@anasereijo I've doubled the size of the image. How does it look to you? I don't have a retina screen to test it on?

**Comment by anasereijo** [comment]
@steverydz ahhh my wonderful screen :)
looks much better now, thanks! but if it makes the page much slower to load just keep as it was

**Pull request merged**
