### PR TITLE
Create openstack features page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Created the openstack/features page and added it to the navigation.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/features](http://0.0.0.0:8001/openstack/features)
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3289

### CODE REVIEW

**Comment by frankiegranato** [comment]
Can we please move 'Features' so it appears second in the secondary menu? I think the menu items should be as follows: Overview | Features | Managed | Training | Storage | Developer | Partners | Install

**Comment by anthonydillon** [comment]
@frankiegranato done

**Comment by anasereijo** [comment]
screen shot 2018-06-21 at 13 42 08

screen shot 2018-06-21 at 11 45 55

screencapture-ubuntu-pr-3385-run-demo-haus-openstack-features-2018-06-21-12_20_31
please make the same amendments to the following sections and alternate white background with light grey to separate them.

**Comment by frankiegranato** [comment]
Lots of amends in the copydoc :-)

**Comment by frankiegranato** [comment]
screen shot 2018-06-21 at 14 12 45
Ordering of items in the menu is still not correct @anthonydillon

**Comment by anthonydillon** [comment]
@anasereijo @pmahnke @frankiegranato done the changes requested.

**Comment by anasereijo** [comment]
screen shot 2018-06-22 at 13 34 52
screen shot 2018-06-22 at 13 58 54
screen shot 2018-06-22 at 14 04 47
screen shot 2018-06-22 at 14 11 38

**Comment by frankiegranato** [comment]
I've asked for a paragraph about Consultancy Services to be made into it's own section. See copydoc for details. Once this is done it will be a +1 from me. 
screen shot 2018-06-25 at 13 36 00

**Comment by anthonydillon** [comment]
@frankiegranato @anasereijo done and ready for review again.

**Comment by anasereijo** [comment]
@anthonydillon

**Comment by anthonydillon** [comment]
Thanks @anasereijo done

**Comment by anasereijo** [comment]
@anthonydillon can you make the "Logging and Monitoring" section same style as what we have on /ai/features? (full width image with card)

**Comment by anthonydillon** [comment]
@anasereijo done

**Pull request merged**
