### PR TITLE
Update /about/contact-us/form to VBT

### LINKED ISSUE #1890: /about-us/contact/form to VBT

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

Update /about/contact-us/form to VBT

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/about/contact-us/form](http://0.0.0.0:8001/about/contact-us/form)
- Check the above page matches the patterns doc

## Issue / Card

Fixes #1890

### CODE REVIEW

**Comment by barrymcgee** [comment]
Demo: http://www.ubuntu.com-1890-about-contact-us.demo.haus/about/contact-us/form

**Comment by yaili** [comment]
- [ ] There is a problem with the arrows in the breadcrumbs (not aligned, too much space in S screen, and missing current page title)
screen shot 2017-06-07 at 14 28 52
screen shot 2017-06-07 at 14 29 50

**Comment by barrymcgee** [comment]
This should be addressed by https://github.com/canonical-websites/www.ubuntu.com/pull/1943

**Comment by barrymcgee** [comment]
Samll screen nav spacing is captured by #1893

**Pull request merged**
