### PR TITLE
Fixing global nav

### LINKED ISSUE #3231: Beta nav: Make global nav fixed to bottom of page on mobile (as per current live site)
screenshot from 2018-05-24 11-04-32
screenshot from 2018-05-24 11-04-43

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Move global nav to bottom of page on mobile

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Resize the browser to mobile size
- See that the global nav is at the bottom of the page and is good

## Issue / Card
Fixes #3231

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz 

- Canonical logo and company are taking us to the same place so maybe we can delete company and keep canonical moving it to the same row after login.

- left align links
screen shot 2018-05-25 at 09 54 55

- left align this section and amend paddings to be the same
screen shot 2018-05-25 at 09 57 10

**Comment by Caleb-Ellis** [comment]
@steverydz @anasereijo Added a couple of commits that fixed the padding, and hid the "Company" link. I also changed the nav breakpoint in global settings to `$breakpoint-medium`, otherwise there was this weird half desktop, half mobile stuff going on between 768px and 875px screen width.

**Comment by anasereijo** [comment]
thanks @Caleb-Ellis, is looking much better.
can you just please delete the left padding on "other websites" content? 
screen shot 2018-06-01 at 15 04 02

**Comment by steverydz** [comment]
@anasereijo The padding has been removed

**Comment by steverydz** [comment]
@frankiegranato I'll make a separate issue about that as it's not part of this task

**Comment by anthonydillon** [comment]
LGTM :+1:

**Pull request merged**
