### PR TITLE
Increase speed on navigation transition

### LINKED ISSUE #3619: Drop-down menu is too slow on beta
The drop-down feels like it takes forever. Go to http://mongoose.ubuntu.com/ and try to get to "Openstack" - it's under "Enterprise".

1. Click "Enterprise"
2. Wait for what feels like eternity
3. Click the big green button when it finally appears

Could we reduce the transition time to 0.5 seconds or so?

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Increase speed on dropdown menus

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- See that the dropdown speed is acceptable

## Issue / Card
Fixes #3619

### CODE REVIEW

**Comment by anasereijo** [comment]
dropdown speed is looking good to me.
we should have the same animation on global nav dropdowns

**Comment by frankiegranato** [comment]
@steverydz I agree with @anasereijo - all dropdown menus should have the same animations. It looks like the products and login dropdowns have a different closing animation. 
Aside from this, the new speed is good +1 form me re the speed of transitions. Please be sure to fix the animation on the global menus too (please be mindful of mobile too).

**Comment by steverydz** [comment]
@anasereijo Done

**Comment by anasereijo** [comment]
@steverydz just noticed that when closing the dropdown the text disappears first which looks weird... I think it was looking ok before.. can you please fix it?

**Comment by steverydz** [comment]
@anasereijo Fixed

**Pull request merged**
