### PR TITLE
Flattened /legal/ubuntu-advantage section

### LINKED ISSUE #4200: Flatten legal pages - Ubuntu Advantage

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Flattened legal ubuntu-advantage section
- Updated navigation
- Updated redirects
- Added some special redirects requested by legal team

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- look at the files in the /legal directory and compare to this [spreadsheet](https://docs.google.com/spreadsheets/d/12kuuGgwRqN3k7wlRc4QKIuZifjvxbynizO_LEjKjBq4/edit#gid=0)

* test the link [/legal/ubuntu-advantage-service-description](http://0.0.0.0:8001/legal/ubuntu-advantage-service-description) and [the old link](http://0.0.0.0:8001/legal/ubuntu-advantage/service-description) redirects also test that [/uasd](http://0.0.0.0:8001/uasd) redirects as well
* test the link [/legal/ubuntu-advantage-service-description/ja](http://0.0.0.0:8001/legal/ubuntu-advantage-service-description/ja) and [the old link](http://0.0.0.0:8001/legal/ubuntu-advantage/service-description-ja) redirects
* test the link [/legal/ubuntu-advantage-assurance](http://0.0.0.0:8001/legal/ubuntu-advantage-assurance) and [the old link](http://0.0.0.0:8001/legal/ubuntu-advantage/assurance) redirects
* test the link [/legal/ubuntu-advantage-service-terms](http://0.0.0.0:8001/legal/ubuntu-advantage-service-terms) and [the old link](http://0.0.0.0:8001/legal/ubuntu-advantage/service--terms) redirects

## Issue / Card

Fixes #4200

### CODE REVIEW

**Comment by anthonydillon** [comment]
Did you rebase this?

**Comment by pmahnke** [comment]
@anthonydillon 	yes, I have rebased

**Comment by anthonydillon** [comment]
This looks like it had commits that are already in master. I'm worried it will cause issues

**Comment by anthonydillon** [comment]
Looks like there has been some very strange commits in master which are not here so the history is different. I think we will need to create a new branch and cherry-pick the expected commits from this branch and force push to your branch or create a new PR.

**Pull request closed without merging**
