### PR TITLE
Openstack page updates features 4212

### PR DESCRIPTION
**Pull request by inuwa**
## Done

Updated openstack/features Page based on [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
 
## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/features](http://0.0.0.0:8001/openstack/features)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- 

## Issue / Card

Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4212

### CODE REVIEW

**Comment by anasereijo** [comment]
I will review this issue once @anthonydillon question is answered as I am a bit confused too. If you need help let me know.

**Comment by inuwa** [comment]
Hi @anthonydillon the issue is a similar issue to that which @Caleb-Ellis had. When you click resolve on the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#), the requested changes are not effected. I think the  [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#) was not edited in suggestion mode that is why. The way to resolve the issue, is to revert the document to comment state and then see what changes need to be effected. I spoke with @caldav about it already. Sorry for the trouble and misunderstanding.

**Comment by anthonydillon** [comment]
Ah ok, can you suit with the person that made the changes and update the copy doc and ask them to provide suggestions next time.

**Comment by inuwa** [comment]
> Ah ok, can you suit with the person that made the changes and update the copy doc and ask them to provide suggestions next time.

Okay. I'll do that. Thank you for the feedback.

**Comment by deadlight** [comment]
@inuwa the copydoc is still not reflecting the content of your changes. Can you make sure that the copydoc is changed and I will review.

**Pull request merged**
