### PR TITLE
Update image on openstack training page

### LINKED ISSUE #3625: /openstack/training - image on hero section looks low res - DEV
please use this image instead: https://assets.ubuntu.com/v1/c45cabb5-ubuntu-openstack-medals.svg

---
*Reported from: http://mongoose.staging.ubuntu.com/openstack/training*

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update image on openstack training page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/training>
- See image in hero has been updated

## Issue / Card

Fixes #3625

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz 👍 
the image looks out of our content grid?
screen shot 2018-07-06 at 11 14 25

**Comment by steverydz** [comment]
@anasereijo Yes, I think that's because of how it was intended to display? What change do you want to make?

**Comment by anasereijo** [comment]
@steverydz please keep the image inside the 12 col grid like we usually do

**Comment by steverydz** [comment]
@anasereijo Done

**Pull request merged**
