### PR TITLE
Change short-terms page to service terms

### LINKED ISSUE #2861: "Short terms" page becomes "Service terms" page
Please see changes in Copydoc: https://docs.google.com/document/d/1W0WJrXaIvC54MDPgS62xfgPhqJaSE7RcZ2mjIqz1Y2o/edit

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Change short terms page to service terms page
- Add redirect for all short terms pages
- Replace hardcoded links to short-terms with service-terms

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/legal/service-terms](http://0.0.0.0:8001/legal/service-terms)
- Make sure page matches [copy doc](https://docs.google.com/document/d/1W0WJrXaIvC54MDPgS62xfgPhqJaSE7RcZ2mjIqz1Y2o/edit)
- Go to <http://0.0.0.0:8001/legal/short-terms> and make sure you are redirected to <http://0.0.0.0:8001/legal/service-terms>

## Issue / Card

Fixes #2861

### CODE REVIEW

**Comment by steverydz** [comment]
@frankiegranato short terms page change done

**Comment by Caleb-Ellis** [comment]
@steverydz @frankiegranato I assume we also want to change the link name in /legal, as well as the name of the breadcrumb in /legal/service-terms to "Service terms"?

**Comment by steverydz** [comment]
@Caleb-Ellis Good catch. Fixed

**Comment by steverydz** [comment]
@Caleb-Ellis Done

**Comment by Caleb-Ellis** [comment]
@steverydz I'm still getting 14 commits for this PR, and I'm pretty sure only the last 2 are related to this - the rest are already in the feature branch. Maybe something happened when the term boxes PR was merged and reverted in master? Honestly not sure what happened. @anthonydillon @deadlight any ideas? Might just be easier to create a fresh PR off the feature branch with the last 2 commits, tbh.

**Comment by steverydz** [comment]
I'll just create a new PR

**Pull request closed without merging**
