### PR TITLE
Clarifies “Enterprise support” navigation links

### PR DESCRIPTION
**Pull request by matthewpaulthomas**
Revises most of the links in the “Enterprise” mega-menu “Enterprise support” section.

## Done

Changes:
- “Enterprise support” to “Support and services”, to avoid repeating “Enterprise”, and to increase findability by people who don’t think of Livepatch, FIPS etc as “Support”
- “Kernel Live Patch” to “Livepatch security updates”, to correct the product name and hint at the benefit
- “Extended Ubuntu security” to “Extended Security Maintenance”, to correct the product name
- “Optimised Windows VMs” to nothing, since there’s nowhere for it to link to (anyone following the link currently would be utterly bewildered)
- “Web-based remote management” to “Landscape remote management”, to include the name of the product.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- In the “Ubuntu” navigation bar, click on “Enterprise”

## Issue / Card

[Services UI design document, phase 1](https://docs.google.com/document/d/1lKMFVBRU4MBFJuiUF5cOFAFsqtWATxgreoSoEc1OuXk/edit#heading=h.8m2l6r3xfhc) (Canonical-only link)

### CODE REVIEW

**Comment by Greggless** [comment]
FYI Peter has a [PR](https://github.com/canonical-websites/www.ubuntu.com/pull/4446) in for updating this Nav too... 

Will fix and merge his version then this.

**Comment by pmahnke** [comment]
@matthewpaulthomas 	have you run changing the header by Thibaut? Otherwise these changes are good (not an official approval, just quick glance)

**Comment by matthewpaulthomas** [comment]
@pmahnke Thanks. I’ve mailed Thibaut (CCing you) for approval of the heading change.

**Comment by matthewpaulthomas** [comment]
I just reminded Thibaut about this. He’s not sure about a couple of the changes, specifically adding brand names where they weren’t before. We agreed that it’s a balancing act between people who don’t know what we offer, who need descriptions; and people who know about a specific service, and are looking for it by name.

Thibaut said he will find 30 minutes to write a proper response.

**Comment by Greggless** [comment]
The typical process is for suggestions to be made in the copy doc, once agreed upon we then update the code. Could you make the suggested changes in the copy doc where they can be discussed by Mark/Thibaut etc, pretty please?

**Comment by matthewpaulthomas** [comment]
@Greggless Done.

**Comment by matthewpaulthomas** [comment]
Initially, when I didn’t know the process, I commented on the copydoc linking to this PR. Mark resolved the comment, but without replying, and didn‘t comment here either. Then you asked me here to propose changes in the copydoc for discussion. I did that, but now you’ve accepted them with no discussion, _and_ closed the PR. So now I don’t know where the discussion is supposed to happen…

Coincidentally, though, I’ll be holding a session at the sprint on Friday discussing the multiple ways we use the term “support” and “Ubuntu Advantage”, with this menu as an example. Maybe that will help to resolve the title change at least. I’ve invited Thibaut.

**Pull request closed without merging**
