### PR TITLE
Update developer menu

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update to latest developer menu

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- See that page matches [the copy doc](https://docs.google.com/document/d/1l6Ywrj_HRcg2-WYKorjRAUE_dvPdwZYPtL4a6z66Uc8/edit#)

## Issue / Card

Fixes [#709](https://github.com/ubuntudesign/web-squad/issues/709)

### CODE REVIEW

**Comment by frankiegranato** [comment]
- [ ] Spacing of dots on the lower links is odd-centre.  
spacing of dots

- [ ] Numerous other little typos and updates in the copydoc

**Comment by steverydz** [comment]
@frankiegranato Fixed

**Comment by frankiegranato** [comment]
@anasereijo can you take a look at this new developer menu please? I realise its not looking very elegant at the moment, but it's following Mark's specific instructions. Please just check for obvious flaws.

**Comment by anasereijo** [comment]
@steverydz some small changes I hope
screen-shot-2018-07-09-at-16 52 04

**Comment by frankiegranato** [comment]
The spacing of these dots still looks off to me @anasereijo 
Fyi @steverydz 
spacing of dots 02

**Comment by steverydz** [comment]
@anasereijo Padding and alignment done. There are no links for those at the moment.

**Comment by steverydz** [comment]
@frankiegranato Try a hard refresh - you might have cached css

**Comment by anasereijo** [comment]
Thanks @steverydz 
I agree with @frankiegranato they seem aligned vertically now but the left and right paddings are not the same?

**Comment by steverydz** [comment]
@anasereijo Try now

**Pull request merged**
