### PR TITLE
Add Ubuntu Budgie flavour

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Added Ubuntu Budge to our list of flavours in the about and in the download sections. 

## QA
- Run `make run`
- Go to http://localhost:8001/about/about-ubuntu/flavours
- Check Ubuntu Budgie is listed
- Then head over to http://localhost:8001/download/ubuntu-flavours
- Check that Ubuntu Budgie has been added to the grid list

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/1407

### CODE REVIEW

**Comment by anthonydillon** [comment]
@yaili @joanasa89 could you please check the screenshot for a design review.

**Comment by joanasa89** [comment]
Can we extend vertical & horizontal lines? As 'ubuntu studio' and 'xubuntu' are floating. 

ubuntu_flavour

**Comment by anthonydillon** [comment]
@joanasa89 Yea sure

**Comment by joanasa89** [comment]
Yes, looks good to me.

**Comment by anthonydillon** [comment]
@joanasa89 do change the label if you are confident its ok.

**Comment by anthonydillon** [comment]
Thanks all :shipit:

**Pull request merged**
