### PR TITLE
Copy updates for openstack consulting

### LINKED ISSUE #3485: Beta updates: /openstack/consulting - pricing changes
As per copydoc: https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Copy changes as per copy doc

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/consulting>
- See that page matches the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)

## Issue / Card

Fixes #3485

### CODE REVIEW

**Comment by shivjoshi1996** [comment]
@steverydz Hey Steve, could you please replace the "Consulting, design and delivery pricing" with an include to  _openstack-consulting.html, found in shared/pricing. This will ensure that the pricing is always consistent.  I'll change the copydoc. Cheers

**Comment by steverydz** [comment]
@shivjoshi1996 Done

**Comment by steverydz** [comment]
@shivjoshi1996 Done

**Comment by frankiegranato** [comment]
Looks good. One small styling request - see attached.
consulting openstack amend

**Comment by steverydz** [comment]
@frankiegranato Done

**Comment by steverydz** [comment]
@frankiegranato It's back up now http://www.ubuntu.com-pr-3495.run.demo.haus/

**Comment by frankiegranato** [comment]
Why is the 'per server per year' text suddenly in italics? 
consulting openstack italics

**Comment by steverydz** [comment]
@frankiegranato That's the style that vanilla uses. I've overridden it for this site now.

**Comment by frankiegranato** [comment]
@steverydz this page is great now but annoyingly I've spotted one more small text edit, so I'll -1. SORRY.

**Comment by steverydz** [comment]
@frankiegranato Done

**Pull request merged**
