### PR TITLE
1579 server overview

### LINKED ISSUE #1579: /server/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /server overview to vbt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/3.%20Server?preview=server-overview.png) and the [demo](http://www.ubuntu.com-1579-server-overview.demo.haus/server)

## Issue / Card

Fixes #1579

### CODE REVIEW

**Comment by yaili** [comment]
Design review:
- [ ] The h3s in the row after "A release schedule you can depend on" are missing the title class
- [ ] Why does the `p-card__title` class (in the "Get in touch" card) have a font-size defined? It should be whatever heading style it's applied - can you check this, because it might be a Vanilla bug that needs to be fixed
- [ ] Centre the ticks and the column headers (LXD, KVM, twice) in the table in "The fast track to virtualisation and containers"
- [ ] Can we use a non-breaking hyphen ( ‑ ) in the word Hyper-V in "The fast track to virtualisation and containers"

**Comment by yaili** [comment]
Design review:
- [ ] The h3s in the row after "A release schedule you can depend on" are missing the title class
- [ ] Why does the `p-card__title` class (in the "Get in touch" card) have a font-size defined? It should be whatever heading style it's applied - can you check this, because it might be a Vanilla bug that needs to be fixed
- [ ] Centre the ticks and the column headers (LXD, KVM, twice) in the table in "The fast track to virtualisation and containers"
- [ ] Can we use a non-breaking hyphen ( ‑ ) in the word Hyper-V in "The fast track to virtualisation and containers"

**Comment by pmahnke** [comment]
@yaili 

- re 'The h3s in the row after' - I changed them because of the wrapping

with

image

with h4s

image

- re 'Why does the p-card__title class' it has always been set to 1.5rem as far as I know... if you don't like that, then it is a Vanilla bug

**Comment by yaili** [comment]
@pmahnke there is a [bug](https://github.com/vanilla-framework/vanilla-brochure-theme/issues/78) on Vanilla Brochure to fix the heading icon alignment, as it's not implemented according to spec - I'll expand that bug to include not setting font size

- [ ] The correct class name for the heading-icon title is p-heading-icon__title - it's missing "-icon" right now

**Comment by pmahnke** [comment]
@yaili I temporarily fixed the icon position and put a note on the issue; however, I still think h3's text wraps funny and h4 would look better.... but there it is.

with p-heading-icon__title

image

with p-heading--four

image

**Pull request merged**
