### PR TITLE
removed all the erroring bits of the magnifying glass svg

### LINKED ISSUE #1947: SVG error appears on all v1 styled pages
## Summary

There is an SVG error appearing on all pages using v1 styling.

## Process

- Go to https://www.ubuntu.com/legal
- Inspect element to pen inspector
- View console
- Observe errors on red

## Screenshot

screen shot 2017-06-08 at 12 19 14

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* used https://validator.nu/ to trim out bad XML bits of the magnifying glass

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Compare the search icon to live

## Issue / Card

Fixes #1947

## Screenshots

live
image

updated
image

### CODE REVIEW

**Comment by pmahnke** [comment]
@joanasa89 [demo](http://www.ubuntu.com-1947-svg-parse-error.demo.haus/)

**Comment by joanasa89** [comment]
Desktop looks good. But tablet & mobile still have the old svg.

**Comment by pmahnke** [comment]
@joanasa89 can you look again?

**Comment by joanasa89** [comment]
Looks good to me. thanks!

**Pull request merged**
