### PR TITLE
New LP for Kubernetes Case Study

### PR DESCRIPTION
**Pull request by Khutch25**
## Done

New page for the new K8s case study to live. Please note the form CTA button will be updated from 'whitepaper' to 'case study' so ignore for now.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)

### CODE REVIEW

**Comment by kwm14** [comment]
@Khutch25 what is the URL so we can review the K8s case study landing page? 😄

**Comment by Khutch25** [comment]
> @Khutch25 what is the URL so we can review the K8s case study landing page? 😄

@kwm14 It's /engage/kubernetes-case-study :)

**Comment by Khutch25** [comment]
@inuwa Waiting for access to the /engage Drive folder to move the copy doc into, but here it is for now: https://docs.google.com/document/d/14gZ0XMP3hZoEVY9xDd41IS9BpW8pNMo_41ELtR2lhpg/edit?usp=sharing

**Comment by inuwa** [comment]
> @inuwa Waiting for access to the /engage Drive folder to move the copy doc into, but here it is for now: https://docs.google.com/document/d/14gZ0XMP3hZoEVY9xDd41IS9BpW8pNMo_41ELtR2lhpg/edit?usp=sharing

@Khutch25 thank you for the link, but I am not sure that it is related to this issue. I noticed that the link @kwm14 posted is for an English page not a german one. I'll try fish out specs in google docs. Cheers

**Comment by inuwa** [comment]
LGTM 👍

**Comment by kwm14** [comment]
## Design review
Looking good @Khutch25 just one small update 😄 
- [ ] can you add `prefix-1` to `col-5` so it gives some space between title and infographic

screenshot 2018-10-25 at 17 18 41

**Comment by kwm14** [comment]
Thanks @Khutch25 LGTM 👍

**Comment by Khutch25** [comment]
@shivjoshi1996 Any reason why this is blocked?

**Comment by shivjoshi1996** [comment]
@khurch25 someone needs to review the code and approve the changes again.@inuwa please approve the changes after you’ve reviewed the code (there is a button where you have to do this, if you can’t find it, ask Caleb).

**Pull request merged**
