### PR TITLE
1582 server livepatch

### LINKED ISSUE #1582: /server/livepatch/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /server/livepatch to vbt
* added .p-card--resource, with no animation - needs design and perhaps better css

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/livepatch)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/3.%20Server?preview=server-livepatch.png) and the [demo](http://www.ubuntu.com-1582-server-livepatch.demo.haus/server/livepatch)

## Issue / Card

Fixes #1582

### CODE REVIEW

**Comment by yaili** [comment]
Design review:
- [ ] Don't like the resource card, it needs work - but do we need it, shall we just use card highlighted and do away with this pattern?
- [ ] At S screen, if the hero background image position was "center center" it would look a bit more interesting - is this possible?
- [ ] There's a gap (1 col, maybe) between right edge of the resource card and the grid, can the card be moved to the right edge of the grip?

**Comment by pmahnke** [comment]
@yaili updated

* removed .p-card—resource and added .p-card__category for icon and doc type - I think it looks ok
* made the hero `background-position: center center;` inline

**Comment by yaili** [comment]
- [ ] The step list in "How to enable the Canonical Livepatch Service" can be col-8 instead of 7
- [ ] I think it's odd that it says Download datasheet but you can't click it, it should only say Datasheet, which is the type of resource, but maybe that means the title needs to be more descriptive

**Comment by pmahnke** [comment]
@yaili regarding the resource card... how about we have a link on the type line as well and just make it grey until hovered or active?

``` html
        <div class="p-card--highlighted  u-float--right">
          <h2 class="p-card__title"><a href="https://pages.ubuntu.com/rs/066-EOV-335/images/20161017_LivePatching_DS_.pdf">Livepatch overview&nbsp;&rsaquo;</a></h2>
          <p class="p-card__content">Download datasheet for more detail on the Canonical Livepatch Service including FAQs.</p>
          <p class="p-card__category"><a href="https://pages.ubuntu.com/rs/066-EOV-335/images/20161017_LivePatching_DS_.pdf">Download datasheet</a></p>
        </div>
```

```scss
  .p-card__category {
    background: url('#{$assets-path}ed42aefa-icon-resource-hub-icon-document.png') left center no-repeat;
    color: $color-mid-dark;
    font-size: $sp-medium;
    line-height: 1.5;
    margin: 0;
    padding: 0 0 0 $sp-large;
    text-transform: uppercase;

    > a:link,
    > a:visited {
      color: $color-mid-dark;
      text-decoration: none;
    }

    > a:hover,
    > a:active {
      color: $color-brand;
      text-decoration: underline;
    }
  }
```

**Comment by yaili** [comment]
@pmahnke that would be different from any muted heading/uppercase usage we have, it's just supposed to be a label - I think at most if it's a link it could be maybe in Insights, or Tutorials, where when you click it it takes you to a list of all the resources in that type/category, does that make sense? Can we remove the link and word Download? 

Should the text in that card be Download _the_ datasheet? Thanks 😅

**Comment by pmahnke** [comment]
@yaili removed... also fixed that text more... it sucked

**Pull request merged**
