### PR TITLE
Update the styling of the Where are Ubuntu users? section

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the Where are Ubuntu users? section mark up. Also, update the world map styling.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/statistics](http://0.0.0.0:8001/desktop/statistics)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check that the map and section styling matches [the design](https://github.com/canonical-websites/www.ubuntu.com/issues/4094)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4124

## Screenshots
screenshot from 2018-10-10 23-34-38

### CODE REVIEW

**Comment by spencerbygraves** [comment]
@anthonydillon it looks good, how have you specified the tints of the brand colours?

**Comment by anthonydillon** [comment]
@spencerbygraves I colour picked from the design. The hex provided didn't match the design.

**Comment by spencerbygraves** [comment]
Spoke with @anthonydillon about using orange and the same increments as the snapcraft version.

**Comment by anthonydillon** [comment]
@spencerbygraves thanks, I've updated the range to match the snapcraft. Could you let me know what the colours should be? Here is the current list:
```
colors: [
          '#FFFFFF',
          '#fed6ca',
          '#eeb2a0',
          '#eb987a',
          '#e26e47',
          '#772953'
        ]
```

**Comment by spencerbygraves** [comment]
@anthonydillon can we start with Ubuntu orange and work down the [tint values as shown on this page](https://design.ubuntu.com/brand/colour-palette/)?

**Comment by anthonydillon** [comment]
@spencerbygraves done

**Comment by spencerbygraves** [comment]
@anthonydillon great, thanks 👍

**Pull request merged**
