### PR TITLE
3881: Merge beta branch into master

### LINKED ISSUE #3881: BETA: Merge beta branch into master branch

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Merged beta branch into master branch
- Fixed up some styling/templating errors on the /engage (English + German) pages
- Temporarily removed `/search` from Travis linkchecker
- Updated Rigado webinar CTA to say "Watch on-demand"
- Small styling fixes

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check the primary nav, secondary nav and global nav work as expected
- Check the following new pages:
  - /openstack + children
  - /kubernetes + children
  - /ai + children
  - /about + children
  - /containers
  - /engage/vmware-to-openstack + /engage/de/vmware-to-openstack
  - /public-cloud

## Issue / Card

Fixes #3881, fixes ubuntudesign/web-squad#764

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
Looking really good @Caleb-Ellis but I have a couple(ish) design updates, in classic Karlos style 😺

### Primary nav - Ubuntu flavours
- [ ] `p-inline-list--middot` looks out of alignment compared to Enterprise, Developer and Community

screen shot 2018-08-15 at 11 18 57

### /openstack 
- [ ] openstack client inline images hidden on mobile (seems to be an ongoing bug 😬)

screen shot 2018-08-15 at 11 27 47

### /openstack/features
- [ ] storage section - two logos are hidden on desktop #logocentral

screen shot 2018-08-15 at 11 34 02

- [ ] networking section inline images hidden on mobile

screen shot 2018-08-15 at 11 37 04

### /openstack/managed
- [ ] bootstack customers section inline images hidden on mobile
screen shot 2018-08-15 at 11 40 17

### Global inline images
- [ ] I think it's safe to say inline images need fixing on mobile across the board so I won't continue adding screenshots, as I'm guessing it will be a global change 👍 or maybe it's a bug in Vanilla...

### /kubernetes
- [ ] Why choose the Canonical distribution section - link inside matrix is too tight to body copy

screen shot 2018-08-15 at 11 49 04

**Comment by Caleb-Ellis** [comment]
@kwm14 Made the updates
- Changed Ubuntu Flavours to a bordered list, and made it a split list because otherwise it gets a bit long
- Added a hot-fix from Vanilla 1.8.0 that mostly fixes the inline images bugs, but some logos will still be messed up. This is an issue with the images themselves having no width or height data.
- Fixed the spacing bug on /kubernetes

**Comment by kwm14** [comment]
Thanks @Caleb-Ellis for the design updates. Re-reviewed and LGTM 👍 💯

**Comment by frankiegranato** [comment]
I've added my +1. I haven't checked over everything (!) but hopefully I've checked the important bits.

**Pull request merged**
