### PR TITLE
Landing page for the 2nd AIML webinar

### PR DESCRIPTION
**Pull request by caldav**
## Done

* [New landing page](http://www.ubuntu.com-canonical-websites-pr-4090.run.demo.haus/engage/deploy-ai-ml-model) based on the successful https://www.ubuntu.com/engage/ai-ml-ubuntu
* [Copy doc](https://docs.google.com/document/d/1BMqxhCOJfT43Mj2MFNgdM0X0c0rUYmBQBLeYFTCKfKY/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Ensure [the page](http://www.ubuntu.com-canonical-websites-pr-4090.run.demo.haus/engage/deploy-ai-ml-model) looks good and is matching the [copy doc](https://docs.google.com/document/d/1BMqxhCOJfT43Mj2MFNgdM0X0c0rUYmBQBLeYFTCKfKY/edit#)

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @caldav 
hey  @caldav ,

- I don't think the blue 'Register now' link is readable on a dark grey background.
- I also think it's odd to have a chevron on an anchor link - maybe try without the chevron? just underlined?

@frankiegranato what do you think?

**Comment by caldav** [comment]
@anasereijo the link has proved popular, especially on mobile, as a "fast track" to the form/video, and I don't think a button would work, because it would be yet another "register" button when you come from the takeover. Your concerns are valid and I'm happy to change, what would you suggest?

**Comment by anthonydillon** [comment]
You could try `p-link--inverted` to make the link stand out in dark backgrounds.

**Comment by caldav** [comment]
@anasereijo about the chevron, now that the link is white, I think it should stay, as a way to make it look clickable. Thoughts?

**Comment by anasereijo** [comment]
Hi @caldav the link is still blue. Can you please make it white? Thanks

**Comment by caldav** [comment]
@anasereijo here is what I'm seeing https://screenshotscdn.firefoxusercontent.com/images/e620d1c7-c1ed-4a0d-a0cd-1d2436055b31.png

**Comment by caldav** [comment]
QA done by Marketing team.

**Comment by caldav** [comment]
@anthonydillon do you mind approving? Can't merge without.

**Pull request merged**
