### PR TITLE
Plans and pricing copy update

### PR DESCRIPTION
**Pull request by shivjoshi1996**
## Done

- Updated copy of plans and pricing page. 
- Updated includes that were featured on plans and pricing page
- Created include for Kubernetes add-ons

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001support/plans-and-pricing/](http://0.0.0.0:8001/support/plans-and-pricing)
- Check that the changes reflect the [copydoc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#) 

## Issue / Card

Fixes: #3437

### CODE REVIEW

**Comment by frankiegranato** [comment]
plans and pricing gap
plans and pricing star
- [ ] Please close up this big gap (see pic)
- [ ] Please try to get asterisk onto the same line as heading if poss (if this is very tricky then just leave it for now) (see pic)
- [ ] There are quite a few other little fixes that I've left commented in the copydoc. All the comments in the copydoc need to be addressed (I've closed the comments that you've already addressed).

**Comment by frankiegranato** [comment]
@shivjoshi1996 please see my new round of comments in the doc. Be sure to catch them all :-)

**Comment by frankiegranato** [comment]
@pmahnke  I've gone through and made sure that all the prices on the beta pages matches the pricing as its described here on the plans & pricing page. I'd be really pleased to have someone else double check as well though. 

The new pages that have prices on them are:  Kubernetes/managed, Kubernetes-index, AI-index and OpenStack/consultancy

Btw I can foresee that maintaining fidelity in the pricing across all these new pages is going to be a pain in the ass in the future.

**Comment by shivjoshi1996** [comment]
@frankiegranato Made the requested changes and I've also spotted a missing link in the copydoc which I've commented you in. Ready for review, lets cross our fingers!

**Comment by pmahnke** [comment]
@shivjoshi1996 once Chris approves, this is good to go

**Comment by cjohnston1158** [comment]
- [ ] Technical Account Manager is a product name, I think that it should be capitalized as is currently live.
- [ ] You can't purchase OpenStack support from buy.ubuntu.com so it seems odd to point someone there and say "Buy Ubuntu Advantage" in the OpenStack section
- [ ] Knowledge Base capitalization is not consistent throughout
- [ ] "AI/ML Add-on for Discover and Discoverer Plus" - should this be Discoverer and Discoverer Plus?

**Pull request merged**
