### PR TITLE
Update alternative downloads page

### LINKED ISSUE #2907: Implement copy for download/alternative-downloads

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add id to headings for linkability
- Remove 'Past ARM releases' section

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/alternative-downloads>
- Make sure 'Past ARM releases' section has been removed
- Make sure section headings have an ID

## Issue / Card

Fixes #2907

### CODE REVIEW

**Comment by steverydz** [comment]
@frankiegranato Done

**Comment by frankiegranato** [comment]
Lovely. +1

**Comment by steverydz** [comment]
@pmahnke Fixed

**Comment by pmahnke** [comment]
@steverydz oh... really sorry, but I don't think there will be a 32-bit 18.04 desktop... I have removed from the copy doc...

**Comment by steverydz** [comment]
@pmahnke No worries. Done

**Pull request merged**
