### PR TITLE
Replace autopilot with conjure up on /download/cloud

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Replaced the content on /download/cloud with the new conjure-up version.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/download/cloud](http://0.0.0.0:8001/download/cloud)
- Check that the copy matches the [copy doc](https://docs.google.com/document/d/1y3uaLNn7dxZKcLq2OmVJ96o3NOqn4OTJflty2GmxV9I/edit#)
- Check the page looks ok

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/2182

### CODE REVIEW

**Comment by pmahnke** [comment]
@anthonydillon really sorry, I should have caught 2 things

- [ ] remove the ebook include as it is on the two deeper pages
- [ ] add the get string to the contact us (note, this is an include for /download/cloud, /download/cloud/try-openstack, /download/cloud/build-openstack

**Comment by anthonydillon** [comment]
@pmahnke 
> Remove the ebook include as it is on the two deeper pages

Frank had a note to remove the ebook from sub pages and add it to the cloud page https://docs.google.com/document/d/1y3uaLNn7dxZKcLq2OmVJ96o3NOqn4OTJflty2GmxV9I/edit?disco=AAAABGJtmtY

> add the get string to the contact us (note, this is an include for /download/cloud, /download/cloud/try-openstack, /download/cloud/build-openstack

Which contact us are you referring too?

**Comment by anthonydillon** [comment]
Ready for re-review.

**Comment by frankiegranato** [comment]
Really sorry - I think I need to change the cta texts. See details in copydoc https://docs.google.com/document/d/1y3uaLNn7dxZKcLq2OmVJ96o3NOqn4OTJflty2GmxV9I/edit#

**Comment by anthonydillon** [comment]
@frankiegranato updated the CTAs. Ready for another review.

**Pull request merged**
