### PR TITLE
V1 cloud overview

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Update /cloud to vbt including new foundation cloud section

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud](http://0.0.0.0:8001/cloud))
- Compare to the [design](https://www.dropbox.com/home/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-overview.png)
- Demo www.ubuntu.com-v1-cloud-setup.demo.haus

## Issue / Card

Foundation cloud: https://trello.com/c/tuTC0Ucn

### Docs

Cloud overview: https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit#

### CODE REVIEW

**Comment by grahambancroft** [comment]
[add foundation cloud to /cloud overview](https://trello.com/c/tuTC0Ucn/3356-add-foundation-cloud-to-%2Fcloud-overview)

**Comment by yaili** [comment]
Design review:
- [ ] Can we make the "A SELECTION OF OUR OPENSTACK CLIENTS" row white?
- [ ] Add border above "Build your production cloud with OpenStack Autopilot"
- [ ] Use inverted link in "Fasttrack to cloud success" and "BootStack is a fully managed private cloud on OpenStack"
- [ ] Is that the correct way to write fasttrack? @pmahnke 
- [ ] Can the subtitle "The bare metal physical cloud" be an h3 with a p-heading--five class? It's not really a paragraph/full sentence
- [ ] "Latest Cloud news from Insights" should have lowercase cloud
- [ ] I think the Juju charms icons need to have a max width or they will be massive at small screen. Do we have a way to do this?

**Comment by yaili** [comment]
- [ ] Needs border above "Latest cloud news from Insights"
- [ ] Add space above "Over 300 services made for Juju" (use the new utility?)
- [ ] If the logos in "LEADING VENDORS PUBLISH ON JUJU" can be updated, that would be good, or are they coming from partners? They're fuzzy and have a white background
- [ ] Any chance the image in "OpenStack and containers office hours" can be after the heading in S screen?

**Comment by yaili** [comment]
@grahambancroft @barrymcgee is it the same demo link, I see no changes

**Comment by barrymcgee** [comment]
@yaili Demo updated: http://www.ubuntu.com-v1-cloud-setup.demo.haus/cloud

**Comment by yaili** [comment]
- [ ] There are 2 images in the OpenStack and containers office hours - should only be 1
- [ ] What is the answer to: "If the logos in "LEADING VENDORS PUBLISH ON JUJU" can be updated, that would be good, or are they coming from partners? They're fuzzy and have a white background" - if an item hasn't been done and design review requested anyway, it would be good to address it so we know what/how to review

**Comment by barrymcgee** [comment]
@yaili Issues addressed, demo rebuilt

**Pull request merged**
