### PR TITLE
18 10 webinar takeover 4284 resolved

### PR DESCRIPTION
**Pull request by inuwa**
## Done

Created 18.10 takeover according to [copy doc](https://drive.google.com/file/d/0B5Jc5K2-I_6xS1E4OWMwd0VNSkx5elJJZWpFMkdEUXhNQk5z/view)
## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check the [design spec](https://github.com/ubuntudesign/design.ubuntu.com-design/issues/15)  and the [copy doc](https://drive.google.com/file/d/0B5Jc5K2-I_6xS1E4OWMwd0VNSkx5elJJZWpFMkdEUXhNQk5z/view) refresh the page until the takeover for 18.10 webinar loads. Make sure that it matches the design documents.

## Issue / Card

Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4284
## Screenshots

image

image

### CODE REVIEW

**Comment by anthonydillon** [comment]
This is due live on the 7th so adding don't merge until then.

**Comment by anthonydillon** [comment]
@inuwa do you have a true design +1 on this one?

**Comment by inuwa** [comment]
> @inuwa do you have a true design +1 on this one?

hi @anthonydillon It is a remade PR. It was already reviewed in previous PR. I had to recreate it because of rebase issues. The to the old PR is [old PR](https://github.com/canonical-websites/www.ubuntu.com/issues/4298).

**Comment by shivjoshi1996** [comment]
@anthonydillon @inuwa After speaking with Marketing, this takeover will go live on the 8th. 

We do need to change the CTA text to "Watch the webinar now" as the webinar will already be live. 

I've updated the copydoc & takeover schedule accordingly.

Cheers

**Comment by inuwa** [comment]
@anthonydillon the changes have been made.

**Comment by anthonydillon** [comment]
@inuwa great, thank you.

**Pull request merged**
