### PR TITLE
Remove more mobile references across the site

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the homepage copy to match the copy doc

## QA
- Pull down this branch and run `./run`
- Make sure the updated heading looks ok.
- Check its matches the copy doc 

## Issue / Card
Copy doc: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit

### CODE REVIEW

**Comment by anthonydillon** [comment]
[Remove more mobile references across the site](https://trello.com/c/sTqANofq/3185-remove-more-mobile-references-across-the-site)

**Comment by yaili** [comment]
There is a "+" in the screenshot which isn't in the copy.

**Comment by deadlight** [comment]
@yaili the plus isn't in the code.

@anthonydillon can you build a demo?

**Comment by deadlight** [comment]
noplus

Here's it rendering without the plus with this version of the code

**Comment by anthonydillon** [comment]
Building demo.

**Comment by anthonydillon** [comment]
Struggling to get a demo working.

**Comment by yaili** [comment]
I removed the full stop from the demo, can you also remove it?

**Comment by yaili** [comment]
Not from the _demo_, from the copy doc.

**Comment by anthonydillon** [comment]
@yaili thanks done.

**Comment by anthonydillon** [comment]
Thanks y'all :shipit:

**Pull request merged**
