### PR TITLE
User report page what lang 4125

### PR DESCRIPTION
**Pull request by inuwa**
## Done
Updated What Language Do they use section to match visual design

## QA

- Check out this feature branch user 
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- go to the url http://0.0.0.0:8001/desktop/statistics
- Check that the layout matches the design https://github.com/canonical-websites/www.ubuntu.com/issues/4094

## Issue / Card

Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4125
## Screenshots

image

Note: Could not use the 16px for the language values in the bar chart. I used a smaller value instead to prevent an overlap. Please see screen shot above to understand more.

### CODE REVIEW

**Comment by spencerbygraves** [comment]
Thanks @inuwa, if we use wider columns, smaller gutters and more of the grid width as in the design, could we use 16px?

If it still doesn't fit with the correct bar sizes, can we use our small text style of 14px please.

Thanks.

**Comment by inuwa** [comment]
image

I reduced the gutter 12px to and increased the fonts to 14px. The scaling does not seem to work for the barchart. If you are okay with the design I'll push the changes

**Comment by spencerbygraves** [comment]
@inuwa I don't think it's quite right yet, let's have another look on Monday. Thanks.

**Comment by inuwa** [comment]
image
Reduced the variance on the colour palette.

**Comment by anthonydillon** [comment]
screenshot_20181014-220019__01

**Comment by inuwa** [comment]
image

Added the responsive horizontal bar charts and realigned the text.

**Comment by spencerbygraves** [comment]
@inuwa thanks, it's looking good except for two things.

I don't think we need the hover on any of the graphs which is changing the colour but not the cursor. Also, the font isn't rendering properly. I've spoken to @anthonydillon about it, he's aware that it exists and will have another look.

Thanks.

**Comment by inuwa** [comment]
@kwm14 This is related to this https://github.com/canonical-websites/www.ubuntu.com/pull/4244 . Issue with conflicts required that we created a separate branch.

**Pull request closed without merging**
