### PR TITLE
3273 nav anchors

### LINKED ISSUE #3273: beta updates: add anchor functionality to primary nav
- when the menu is expanded and you leave the page and then return via the back-button in the browser, the menu is still expanded on the page
- perhaps use anchor links

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Remember nav state when leaving page

This PR is branched from https://github.com/canonical-websites/www.ubuntu.com/pull/3315 and therefore should be merged after that PR

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Open one of the navigation tabs, then click a link to another page
- Hit the browsers back button and see that the previously selected menu is open
- Close the menu by clicking the active tab or the overlay beneath it
- Go to another page
- Hit the back button and see that the menu is still closed

## Issue / Card

Fixes #3273

### CODE REVIEW

**Comment by steverydz** [comment]
This PR should be merged after https://github.com/canonical-websites/www.ubuntu.com/pull/3315

**Comment by anasereijo** [comment]
@steverydz looks good to me 👍 
@frankiegranato do we want to do the same on Products?

**Comment by steverydz** [comment]
@Caleb-Ellis I think that will be horrendously complicated - we'd have to find a way of storing the state of the menu with JS in that case.

Essentially this is why I don't think this persistent menu functionality is a good thing at all - it's not what dropdowns typically do and it creates a whole load of other UX issues.

**Comment by frankiegranato** [comment]
@Caleb-Ellis & @steverydz after a discussion with Peter and Spencer and Caleb, we have agreed to go ahead with this version (even though, I can see that the browser-back/forth functionality is a bit messed up). Lets add this to the 'fix-it-later' list :-)  +1 from me.

**Pull request merged**
