### PR TITLE
update /desktop/partners to vbt

### LINKED ISSUE #1661: /desktop/partners/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /desktop/partners to vbt
* added an ‘is-compact’ class to pull quotes added as a [Vanilla proposal](https://github.com/vanilla-framework/vanilla-framework/issues/1108)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/desktop/partners)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/5.%20Desktop?preview=desktop-partners.png) and the [demo](http://www.ubuntu.com-1661-desktop-partners.demo.haus/desktop/partners)

## Issue / Card

Fixes #1661

### CODE REVIEW

**Comment by yaili** [comment]
- [ ] The link in "Intel® Compute Stick with Ubuntu" should be inverted
- [ ] The ® in "Intel® Compute Stick with Ubuntu" is not correctly aligned and is too small - do we need to review superscript in Vanilla? This should be working out of the box, the font size can't be defined in rems here, it needs to be ems
- [ ] The text colour in the button in "Considering buying new devices with Ubuntu?" should be grey, not aubergine
- [ ] Can we restrict the image size in "Considering buying new devices with Ubuntu?" to about half the container width in S screen? Is there a utility for that?
- [ ] Add some space below title "Commercial information"

**Comment by pmahnke** [comment]
@yaili 
- created a bug for [sup](vanilla-framework/vanilla-framework#1109)
- created a utility for responsive images
- made —accent buttons grey

**Comment by spencerbygraves** [comment]
Can we make the accent button white with grey hover please, as on the live Containers page.

**Comment by pmahnke** [comment]
@spencerbygraves updated p-neutral--button

**Comment by yaili** [comment]
@pmahnke I've refreshed the page a few times and the button in the strip accent still has an aubergine text colour - strip colours shouldn't interfere with button styles - can you confirm this has been removed from the code everywhere - whether just ubuntu.com or brochure theme?

**Comment by pmahnke** [comment]
@yaili I will fix the button in another PR

**Comment by pmahnke** [comment]
@yaili see #1969

**Pull request merged**
