### PR TITLE
Sticky beta navigation demo

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Demo of first pass at making the beta nav sticky. Looking for Design + UX feedback before I tidy the code and bugs up.
- On scroll down, nav disappears - on scroll up, nav comes into view and sticks to the top of the page as per discussion on #2739. @kwm14 using Vanilla easing of course :)
- Main page content disappears when nav dropdown is open. I think this is fine because the nav is so huge and text-heavy that you'd barely see the page content anyway
- Ignore the code. It's a buggy mess but will be fixed once Design/UX is closer to finalised

### CODE REVIEW

**Comment by spencerbygraves** [comment]
@Caleb-Ellis thanks, looking good.

When I first scroll down, the nav is sticky for a little while until I scroll a bit further. Is that deliberate? It seems a bit odd to me and could be removed I think.

Ideally i think the page content should remain, so a user could scroll beyond the open menu and click off to close the menu. I thin we should ask @frankiegranato what she thinks on this.

Thanks

**Comment by Caleb-Ellis** [comment]
@spencerbygraves The initial stickiness was deliberate. I thought it might be a nice UX thing to let the user know that the nav _is_ actually sticky, and it disappears when you scroll down. But I've removed it now and agree it feels better without hahaha

**Comment by frankiegranato** [comment]
After discussing this with @Caleb-Ellis and @spencerbygraves, we all agree that its best to leave the interaction as it is for now. There is no point doing an involved and time-consuming investigation into how to make a sticky nav work with expanded drop downs, before we've tested the BETA. Also, we've heard rumours that @pmahnke has received some direction from Mark about exploring the use of a darker primary nav (which might have beneficial implications for the drown downs) so we'll come back to this discussion once that exploration was been done. 
For now, we've advised @Caleb-Ellis to remove the bottom margin from dropdown window and leave it at that for now.

**Comment by frankiegranato** [comment]
It looks good with removed bottom margin from dropdown window. 
Lets close this issue for now but please keep this demo running.

**Pull request closed without merging**
