### PR TITLE
2666: Move /cloud/public-cloud to /public-cloud and update copy

### LINKED ISSUE #2666: Build of /public-cloud section

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Moved /cloud/public-cloud to /public-cloud
- Updated copy according to [copydoc](https://docs.google.com/document/d/1Bttn4V27eEJjgWzMSY4w9nISTQvvaNYq9CvoWXPOYPs/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/public-cloud
- Check that it matches the [copydoc](https://docs.google.com/document/d/1Bttn4V27eEJjgWzMSY4w9nISTQvvaNYq9CvoWXPOYPs/edit#)
- Check that /cloud/public-cloud redirects to /public-cloud

## Issue / Card

Fixes #2666

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
All looks good just one copy update 😄 
### Why use Ubuntu Server in the cloud?
- [ ] paragraph in cloud and server card doesn't match what's seen in copy doc [here](https://docs.google.com/document/d/1Bttn4V27eEJjgWzMSY4w9nISTQvvaNYq9CvoWXPOYPs/edit#)

**Comment by Caleb-Ellis** [comment]
@pmahnke Alright changed the base branch to beta, but the demo still _looks_ like master because it's missing all the beta commits. Anyway I currently have the page in /public-cloud/index.html - do you mean I should have it as /public-cloud.html?

**Comment by kwm14** [comment]
Thanks @Caleb-Ellis design 👍

**Comment by pmahnke** [comment]
@Caleb-Ellis approved, but CI failing

**Pull request merged**
