### PR TITLE
Remove news page from Kubernetes docs

### PR DESCRIPTION
**Pull request by evilnick**
## Done

remove templates/kubernetes/docs/news.md
Adjust navigation in templates/kubernetes/docs/shared/_side-navigation.md

The news page doesn't really belong in documentation and won't be updated

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- check that the news page is no longer listed in the navigation

### CODE REVIEW

**Comment by anthonydillon** [comment]
Do you also want to have it redirected anywhere?

**Comment by evilnick** [comment]
Done. We don't need a redirect.

**Comment by pmahnke** [comment]
@evilnick the linkchecker is failing as there is a link on the [index page's What's new section](/kubernetes/docs/index.md#whats-new) to news

**Comment by evilnick** [comment]
thanks. was just looking at that :)

**Pull request merged**
