### PR TITLE
Build community section

### LINKED ISSUE #2724: Update /about page
## Summary

- please update the page based on the existing /community/index.html page - the copy has also been updated [here](https://docs.google.com/document/d/1NvYOhOJzdY5ypifTPs73vH5Nb7rFABRWMzjXyDUQt_U/edit#heading=h.legxy5p18gzw)

### LINKED ISSUE #2725: Update the /community page
## Summary

We need to move and update this page into the new /about page and update this page with this [copy doc](https://docs.google.com/document/d/18sNzCqHj8Nf1w-JKRfnM9bvMaz2uZPPDgj_DISgJ30A/edit#heading=h.zeb3a17c2hyu)

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Built new community pages and moved some from /about:
  - /community
  - /community/canonical
  - /community/code-of-conduct
  - /community/debian
  - /community/diversity
  - /community/governance
  - /community/mission

- Updated /about with new [copy](https://docs.google.com/document/d/1NvYOhOJzdY5ypifTPs73vH5Nb7rFABRWMzjXyDUQt_U/edit#heading=h.legxy5p18gzw)
- Moved /about/licensing to /licensing

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Check there is a link to the new community pages in the footer
- Check that the secondary nav breadcrumbs work as intended
- Check all new community pages are present
- Check that the licensing page now lives at /licensing

## Issues

Fixes #2724, fixes #2725

### CODE REVIEW

**Comment by frankiegranato** [comment]
@pmahnke I've added my +1 here, but I think it would be a good idea for you to review these changes too.

**Comment by kwm14** [comment]
## Design review

Only a few design changes/questions to be made 😄 

### community/canonical
- [ ] link currently is style two ways - remove (>) and leave external icon 
screen shot 2018-02-19 at 12 40 30

### community/code-of-conduct
- [ ] spacing on the list between end of paragraph and next title looks tight...is this using Vanilla?

screen shot 2018-02-19 at 12 42 35

**Comment by Caleb-Ellis** [comment]
@kwm14 I've address all design issues except the hero image one. This PR is pretty much just changing copy and moving pages from /about to /community - I feel like updating the design of the pages should be a separate issue?

**Comment by kwm14** [comment]
Thanks for updating @Caleb-Ellis looks good 👍

**Comment by kwm14** [comment]
Thanks for updating logo 👍

**Pull request merged**
