### PR TITLE
3356 kubernetes overview page

### LINKED ISSUE #3356: Beta: Build Kubernetes overview page
[copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#heading=h.rwbysadp6cca)

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update `/kubernetes`

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes>
- See that it matches the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)

## Issue / Card

Fixes #3356

### CODE REVIEW

**Comment by anasereijo** [comment]
please make the following amends:

screen shot 2018-06-21 at 16 34 57

screen shot 2018-06-21 at 17 13 00

screen shot 2018-06-21 at 16 52 41

screen shot 2018-06-21 at 16 55 31

**Comment by frankiegranato** [comment]
Please make amends as specified in copydoc: 

- [ ] Make the 'Kubernetes consulting' prices into cards.

- [ ] Add "Optional add ons" inside the price cards.

NOTE TO SELF: I must check back into this doc to see what Carmine comes back with re the comments about the 'optional add on' section.

**Comment by anasereijo** [comment]
amends:
(also check copydoc)
screencapture-ubuntu-pr-3388-run-demo-haus-kubernetes-2018-06-22-10_40_14

**Comment by steverydz** [comment]
@anasereijo @frankiegranato Changes done

**Comment by pmahnke** [comment]
@steverydz the table isn't quite right.  I have updated it in the copy doc to match what is being asked on the /support/plans-and-pricing page

**Comment by pmahnke** [comment]
@steverydz one ci error and this is good to go.

**Comment by steverydz** [comment]
@pmahnke Thanks. That CI error is expected as the ai pages don't exist yet. We want to keep the links in so we don't accidentally go live with missing pages/broken links.

**Pull request merged**
