### PR TITLE
Beta nav [work in progress]

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Update beta nav to address design review meeting feedback. (https://github.com/ubuntudesign/meeting-notes/issues/265)

Will add more detailed explanation tomorrow.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by anthonydillon** [comment]
@lyubomir-popov should this be merged into the beta branch? Currently, is targeted at master.

**Comment by lyubomir-popov** [comment]
@anthonydillon yes, against beta. is there a way to retarget it? or should I just close and make an ew one?

**Comment by anthonydillon** [comment]
@lyubomir-popov I have retargeted this PR but there are still a lot of changes? Did you branch from the `beta` branch?

**Comment by lyubomir-popov** [comment]
@anthonydillon not the beta, but a merge of 4 branches that @Caleb-Ellis and @steverydz did:
• current master with 18.04 changes
• beta
• vanilla fixes me and @Caleb-Ellis have been working on
• my modifications to the beta nav

the name of that branch was beta-1.7.0

**Comment by Caleb-Ellis** [comment]
@anthonydillon Yeah as @lyubomir-popov said I rebased `beta` with a few different branches and called the result `beta-1.7.0`. When we're happy with the nav on the `beta-1.7.0` branch I think we can just force push it to `beta`, at which point we can delete `beta-1.7.0`.

**Comment by pmahnke** [comment]
@lyubomir-popov this does diverge from the [IA doc of Mark's](https://docs.google.com/document/d/14EJRVoh2Hfc_K3ZFZbPPRkqeZ_NQUwDJp9vnyIuadf4/edit) pretty heavily there aren't the three 'cards' for openstack, k8s and support and you have moved the grey right to the bottom.... I could potentially see the grey at the bottom, but we need the cards on the top for sure

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis any idea why this causes so many travis errors? I haven't touched any of the files that 404

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov Try rebasing this branch with the most recent version of beta-1.7.0. I fixed the errors in #3107 - basically there are some outdated links for openstack in the nav (openstack/managed-cloud -> openstack/managed, openstack/foundation-cloud -> openstack/consulting)

**Comment by lyubomir-popov** [comment]
@pmahnke by cards do you mean these 3?

screen shot 2018-05-03 at 10 30 23

Will add them and put up another demo. (They weren't in the original beta nav implementation, so kept them out to be able to compare the height of the menu before / after and ensure the new version is smaller).

Some background on the proposed layout changes. My first pass at this was very close to the original google doc (screenshot below), and we planned to have it as a fallback in case Mark doesn't like the reorganised layouts.


 
But after arriving at this I felt there are still a few issues - 
• Most of the text is in short sentences. This leaves a lot of white space on the ragged edge of the text, and if the goal is to make things as dense and compact as possible, narrow columns can do that better. (For example, the height of the enterprise tab content is about 3 rows shorter than the original, and there's room for further reduction should that be necessary) For example, further reducing a couple of margins on a vertical media query can make all the info fit an ipad screen (1024x768):

0 0 0 0_8001_internet-of-things_gateways

• Presented in columns, the order of the grouped items (vertical) goes against the natural way of reading (horizontal). Vertical dividers address this, but also add business, especially in such dense layouts.

So we discussed in the design review meeting with Markus Spencer and Frankie and decided to propose this layout as primary for testing, and have a fallback pr with the original layout in case Mark doesn't like this. Happy to make further modifications to both versions.

**Comment by pmahnke** [comment]
@lyubomir-popov and @frankiegranato sorry, still in meeting

I think your first version is lovely and much closer to mark's vision.  I would love it if you could:

1. revert to this version
2. try the cards and removed the duplicated openstack, k8s and support sections
3. use a lighter grey on the primary bar

I do like your version, but I am afraid our tests might be ignored if we use it.  Your first version is really lovely, despite the issues you point out.

thanks

**Comment by lyubomir-popov** [comment]
@pmahnke ok sure, will revert and update the pr.

**Comment by lyubomir-popov** [comment]
@pmahnke @frankiegranato I've done 1 and 3, and from 2 I've added the cards but need confirmation on which bits to remove. Pls see below.

> revert to this version
> try the cards and removed the duplicated openstack, k8s and support sections
> use a lighter grey on the primary bar

Remove lines with '?' or whole section?
Containers
Both Google and Azure Kubernetes use Ubuntu, so Canonical’s distribution is the best choice for portable multi-cloud container operations.
? Install and operate Kubernetes
* Use LXD for legacy apps in containers
* Learn about Docker
? Kubernetes consulting and services

Remove whole section?
OpenStack
The number one platform for OpenStack.
* Fully managed Openstack
* Consulting on cloud architecture
* Training on openstack operations
* Step-by-step install instructions

Remove last line?
Public cloud
The leading cloud and container guest OS.
* optimised images on AWS, Azure, Google, Oracle and IBM clouds
? worker nodes for Google Kubernetes and Azure Kubernetes

Remove this? 
*  Extended Security Maintenance for up to 10 years coverage
* Canonical Livepatch applies critical kernel security fixes without reboot
Management
* Enterprise support from Canonical
* Juju manages multi-cloud deployment and operations
* Landscape, rated the best Linux management system

**Comment by pmahnke** [comment]
@lyubomir-popov looking really nice.

I have updated the copy doc... move a few things around.  we can have steve update if you want - https://docs.google.com/document/d/14EJRVoh2Hfc_K3ZFZbPPRkqeZ_NQUwDJp9vnyIuadf4/edit#heading=h.ex1ot64lbwkh 

Also, the line in the ubuntu ---- (cloud~containers~etc) lockup should be hidden when you don't see the secondary nav (like the homepage)

**Comment by lyubomir-popov** [comment]
@pmahnke I've done the copy changes and moved the line to the lower part of the lockup, so it only appears when it is there. 

Also, here's the alternative version as a separate pr:
https://github.com/canonical-websites/www.ubuntu.com/pull/3126

**Pull request merged**
