### PR TITLE
Export prometheus metrics for feed requests

### PR DESCRIPTION
**Pull request by nottrobin**
Feeds should now output prometheus metrics. [Example](https://pastebin.ubuntu.com/=64Gjt8gThT/)

QA
--

``` bash
./run build  # Just make sure all dependencies are up to date
./run exec --expose-port 8001 --expose-port 9990 --env DJANGO_DEBUG=false ./manage.py runserver --noreload 0.0.0.0:8001
```

Now browse around the site a while at http://127.0.0.1:8001.

Then go to http://127.0.0.1:9990 and inspect the prometheus metrics. Particular look for:

- `feed_request_latency_seconds_bucket`
- `feed_requested_from_cache`
- `feed_failed_requests` - you may not see this if there haven't been any errors

### CODE REVIEW

**Comment by anthonydillon** [comment]
@nottrobin `http://127.0.0.1:9990/` isn't loading for me

**Comment by nottrobin** [comment]
@anthonydillon did you run the right command above? You didn't just do `./run`?

**Comment by anthonydillon** [comment]
Ran
``` 
./run clean
./run build
./run exec --expose-port 8001 --expose-port 9990 --env DJANGO_DEBUG=false ./manage.py runserver --noreload 0.0.0.0:8001
```

Browsed around some then went to: http://127.0.0.1:9990/

I get an error page: The connection was reset

**Comment by nottrobin** [comment]
@anthonydillon that's odd. We'll have to look tomorrow.

**Comment by anthonydillon** [comment]
QA worked in the office.

**Pull request merged**
