### PR TITLE
V1 cloud partners

### LINKED ISSUE #1614: /cloud/partners/ to VBT

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

/cloud/partners to vbt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud/partners](http://0.0.0.0:8001/cloud/partners))
- Check the page against the design https://www.dropbox.com/home/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-partners.png

## Issue / Card

Fixes #1614 

Design: https://www.dropbox.com/home/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-partners.png

### CODE REVIEW

**Comment by barrymcgee** [comment]
Should there be two Juju logos?

screen shot 2017-06-05 at 11 13 25

**Comment by yaili** [comment]
@grahambancroft the demo link isn't working

**Comment by grahambancroft** [comment]
@barrymcgee fixed the juju logo issue

**Comment by grahambancroft** [comment]
@yaili demo here http://www.ubuntu.com-v1-cloud-partners.demo.haus/cloud/partners

**Comment by yaili** [comment]
Design review:
- [ ] In the final row, charm and learn more about should be lowercase
- [ ] Remove chevron from contextual footer button - is it possible to check if this across the site too?
- [ ] Is there any way to reduce the size of the SME logo in "A SELECTION OF OUR CLOUD PARTNERS" - maybe adding padding in the image itself?

**Comment by WillMoggridge** [comment]
Demo: http://www.ubuntu.com-pr-1913.run.demo.haus/

**Comment by barrymcgee** [comment]
@yaili Final point - this feed comes from partners so would need to be updated there

All other points addressed and demo updated.

**Comment by yaili** [comment]
The demo links aren't working.

**Comment by barrymcgee** [comment]
@yaili Demos should be back up now.

**Pull request merged**
