### PR TITLE
New maas pricing

### PR DESCRIPTION
**Pull request by deadlight**
## Done
Added new MAAS pricing table

## QA
- `./run`
- Visit [the maas page](http://localhost:8001/server/maas)
- Check the maas support price table against the [copydoc](https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit#)

### CODE REVIEW

**Comment by deadlight** [comment]
@nottrobin other price tables don't have prices bolded so we're going to leave that decision to the design/UX review.

**Comment by nottrobin** [comment]
@deadlight okay I'll approve this from a code / QA perspective then.

**Comment by frankiegranato** [comment]
Please amend heading as per copydoc :-)

**Comment by deadlight** [comment]
@frankiegranato updated the demo

**Comment by frankiegranato** [comment]
+1 :-)

**Pull request merged**
