### PR TITLE
update /download/desktop to VBT

### LINKED ISSUE #1625: /download/desktop/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* converted /download/desktop to VBT
* added temp css to make brand button text white

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
* [test page](http://0.0.0.0:8001/download/desktop)
* [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/9.%20Download?preview=download-desktop.png)
* [demo](http://www.ubuntu.com-1625-download-desktop.demo.haus/download/desktop)

## Issue / Card

Fixes #1625

### CODE REVIEW

**Comment by barrymcgee** [comment]
@pmahnke Made some hygiene tweaks to code - indentation, added missing alt tags and remove redundant row classes.

Initial QA looks good though it seems strip spacing might be off but I'll leave for Design Review to verify.

**Comment by yaili** [comment]
Design review notes:
- [ ] Download card h2 title should just be an h2
- [ ] Can we sentence case the abbr Long-term support?
- [ ] There's too much space between the two download blocks, it should be more like on live and probably without a strip in between them
- [ ] Why does our abbr underline look weird, even in normal paragraph text? (see image)
screen shot 2017-05-19 at 15 56 48

- [ ] Need border between the download hero (after the 2 cards) and between the two other sections
- [ ] Contextual footer needs external link icons
- [ ] The h1 of the page can be in an 9 or 10 col so it doesn't need to wrap straight away in M screens
- There is an issue with the alignment of the icons in heading icon but I'll add it to Vanilla
- [ ] In [my notes for this page](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/9.%20Download?preview=download-desktop.png) I had recommended that the h2s inside the download cards were full width, which would mean that the download button wouldn't need any special spacing to align with the content on the left - does this make sense?

**Comment by pmahnke** [comment]
@yaili on the abbr, we have `text-decoration: underline dotted;` that comes from [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) see line 113... we might need to update this?  I will add it to ubuntu.com for now, but do you want it fixed in vanilla or vbt?

**Comment by yaili** [comment]
I think it should be in Vanilla if we're doing anything to it.

**Comment by yaili** [comment]
This isn't ready for review, is it? First item still looks the same here.

**Comment by pmahnke** [comment]
@yaili sorry, I forgot to update the [demo](http://www.ubuntu.com-1625-download-desktop.demo.haus/download/desktop) it is there now.

**Comment by yaili** [comment]
- [ ] The title of the abbr is still lowercase, it should be sentence case, and the reference to long-term support in the middle of a sentence should not be titlecase (in the first paragraph of the first card)
- [ ] Need border between "Easy ways to switch to Ubuntu" and "Get the version you need"

**Comment by pmahnke** [comment]
@yaili updated... I fixed that sentence case in another PR... sorry

**Pull request merged**
