### PR TITLE
Appelix takeover

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Build the Appelix takeover

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Refresh until you see the Appelix takeover
- Check the takeover copy matches the [copy doc](https://docs.google.com/document/d/1I8TUiG_u1tksV1ElqzTTaO5ECjdVhKiA1Y71HRAWfMc/edit)
- Check it matches [the design](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/166#issuecomment-439872559)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4380

### CODE REVIEW

**Comment by anasereijo** [comment]
@anthonydillon amazing! I love it. 🥇 

just 2 tiny things:
- [ ] can you make the text `class="col-7"` as requested and image `class="col-5"` 

- [ ] not sure if it is just on my computer but when the page is loaded the drone is already there and then fades out before the animation starts. I think it looks weird. Is there anything you can do?

**Comment by Greggless** [comment]
- UX+1
- 😍 the drone is cooool, but it flips/mirrors at the last frame

**Comment by shivjoshi1996** [comment]
@anthonydillon We need to update the CTA to the landing page (which is being built today by @caldav), before we push this live tomorrow.

**Comment by caldav** [comment]
@shivjoshi1996 sure:
 `/engage/industrial-drones?utm_source=takeover&utm_campaign=FY19_IOT_Robotics_WBN_Apellix`

**Comment by anthonydillon** [comment]
Please check the last two commits are good and match the state of the [content tracker document](https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit).

**Pull request merged**
