### PR TITLE
Whitepaper on the web

### LINKED ISSUE #4782: Whitepaper on the web - build

### PR DESCRIPTION
**Pull request by pmahnke**
## Done
Built the robotics whitepaper.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/whitepapers/robotics](http://0.0.0.0:8001/whitepapers/robotics)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to /whitepapers/robotics
- Check that looks ok
- Check on small screens
- Check it matches [the whitepaper](https://drive.google.com/file/d/1pk8j0wuPsfwmaRSrTwaU8MTH_frFX2EV/view?usp=sharing)

## Issue / Card
Fixes #4782

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke I think the best way to review this is if we do it together? Might be quicker and easier. What do you think?

**Comment by anasereijo** [comment]
[copydoc](https://docs.google.com/document/d/1D7PNArU7cwFzT83Bxf_D_QAZJzRH1mHsXRUdSfS7_ZQ/edit#) with notes and amendments from meeting with @caldav

**Comment by anasereijo** [comment]
links and button missing from 'Further reading'

**Comment by anthonydillon** [comment]
Turns out [baffle.js](https://camwiegert.github.io/baffle) has a [limitation of removing links and buttons](https://camwiegert.github.io/baffle/#basics) when revealing the content.

> baffle operates on node.textContent, so it will flatten any child elements. It's best used on elements without children.

**Comment by steverydz** [comment]
Could we implement our own solution? Save the html within the container as a variable, create a copy, turn into an array and randomise, then replace it?

**Comment by steverydz** [comment]
Could we implement our own solution? Save the html within the container as a variable, create a copy, turn into an array and randomise, then replace it?

**Comment by anthonydillon** [comment]
Super seeded by https://github.com/canonical-websites/www.ubuntu.com/pull/4924

**Pull request closed without merging**
