### PR TITLE
Embedded dynamic form

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Move the current embedded form into the correct structure.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to /core and /internet-of-things
- Check the contact buttons/links open the interactive form
- Submit the form and check it goes through

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4593

### CODE REVIEW

**Comment by deadlight** [comment]
I get the same on this branch as described in #4609

**Comment by anasereijo** [comment]
@anthonydillon when the modal is bigger than my screen it doesn't display the top section and doesn't let me scroll up. see screenshot below:
screenshot 2019-01-30 at 14 56 07

**Comment by anthonydillon** [comment]
@anasereijo this issue is addressed in #4609

**Comment by anthonydillon** [comment]
@deadlight fixed

**Pull request merged**
