### PR TITLE
DO NOT MERGE: Testing AccessLint

### PR DESCRIPTION
**Pull request by anthonydillon**

### CODE REVIEW

**Comment by WillMoggridge** [comment]
I'm not sure it is working :(

**Comment by anthonydillon** [comment]
Think your right. 😞

**Comment by anthonydillon** [comment]
Will leave it and see if it resolves

**Comment by ckundo** [comment]
Hi friends, pardon the interruption, I'm on the AccessLint team. I'm taking a peek at this now.

**Comment by ckundo** [comment]
Hi again, I delivered a fix for this issue. Sorry that this held you up. We're around if you need us, please don't hesitate to ping via GitHub, Twitter, or support@accesslint.com.

**Comment by anthonydillon** [comment]
@ckundo thank you very much for fixing this issue. Glad to hear it was a blip.

**Comment by anthonydillon** [comment]
@ckundo interesting that AccessLint found and commented on an issue but did not fail the CI. Is this normal?

**Comment by ckundo** [comment]
@anthonydillon yes, that's expected behavior. We see AccessLint as a Code Review tool more than CI.  AccessLint can educate contributors and hold folks accountable through reviews, but we leave it up to the teams judgement how to proceed.

**Comment by nottrobin** [comment]
Interesting approach. So we could use this in combination with a CI step running pa11y or similar.

**Comment by anthonydillon** [comment]
@ckundo thanks. Good to know.

**Comment by anthonydillon** [comment]
@nottrobin yea I think we should include `pa11y-ci` to the CI along with AccessLint. Closing this test as successful 🎉

**Pull request closed without merging**
