### PR TITLE
Add animation to Ubuntu product month takeover

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Added animation to Ubuntu product month takeover

## QA

- Pull code and run `./run`
- Check that the takeover has a little animation
- Check that it works in [all browsers we support](https://github.com/canonical-webteam/practices/blob/master/coding/browser-support.md)

### CODE REVIEW

**Comment by anthonydillon** [comment]
I think it looks nice :clap:

**Comment by frankiegranato** [comment]
Nice.

**Comment by spencerbygraves** [comment]
@Caleb-Ellis thanks, looks great! My only thought is it could be a fraction quicker, as on [canonical/products](https://www.canonical.com/products)

**Comment by anthonydillon** [comment]
Tested across ios and android. Firefox, Chrome, Opera, Edge and IE. All :+1:

**Pull request merged**
