### PR TITLE
fix flavours page bugs

### LINKED ISSUE #1516: fix /about/about-ubuntu
## Summary

* breadcrumb not highlighted
* ampersand and caps in Budgie
* remove Edubuntu
* order flavours alphabetically
* s/Localizations/Localisations/

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* breadcrumb not highlighted
* ampersand and caps in Budgie
* remove Edubuntu
* order flavours alphabetically
* s/Localizations/Localisations/

## QA

1. go to [/about/about-ubuntu/flavours](http://www.ubuntu.com-1516-about-ubuntu-fix.demo.haus/about/about-ubuntu/flavours)
2. see that the breadcrumb nav highlights
3. see the text changes

## Issue / Card

Fixes #1516

### CODE REVIEW

**Comment by anthonydillon** [comment]
@pmahnke The demo seems unhappy.

**Comment by barrymcgee** [comment]
The only issue I see is that http://ubuntubudgie.org seems to be down?

http://downforeveryoneorjustme.com/ubuntubudgie.org

**Comment by pmahnke** [comment]
@barrymcgee it is up now... must have been a thing.

**Comment by joanasa89** [comment]
Design  👍

**Pull request merged**
