### PR TITLE
Colour literals

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Replace hex colours with variables

## QA

Check that the variables that replace the hex are the same or very similar

### CODE REVIEW

**Comment by anthonydillon** [comment]
Approved but will hold off merging for you @grahambancroft as CI is failing.

**Comment by deadlight** [comment]
we need to update the Sass test to just test styles.scss

**Comment by anthonydillon** [comment]
Triggering CI again.

**Comment by barrymcgee** [comment]
Given this is now pretty outdated and will be superseded by upcoming Vanilla migration, can it be closed?

**Comment by anthonydillon** [comment]
Closing this as it will be picked up in the update this iteration.

**Pull request closed without merging**
