### PR TITLE
update /info/release-end-of-life to vbt

### LINKED ISSUE #1576: /info/release-end-of-life to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /info/release-end-of-life to vbt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/info/release-end-of-life)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/13.%20Misc?preview=info-release-end-of-life.png)

## Issue / Card

Fixes #1576

### CODE REVIEW

**Comment by yaili** [comment]
@pmahnke this demo isn't working

**Comment by pmahnke** [comment]
@yaili demo - http://www.ubuntu.com-1576-info-release-end-of-life.demo.haus/info/release-end-of-life

**Comment by yaili** [comment]
Design review:
- [ ] There is an empty breadcrumb container on the page
- [ ] The small screen table in "Ubuntu OpenStack release end of life" needs empty tds in the column  "Extended customer support"

**Comment by pmahnke** [comment]
@yaili I removed the breadcrumb box for any page that doesn't have breadcrumbs and added empty cells

**Pull request merged**
