### PR TITLE
Update /download/server/thank-you for landscape-self-service

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add the "Your next steps with Ubuntu Server" section.

## QA
- Pull code and run `./run`
- Go to http://0.0.0.0:8001/download/server/thank-you
- Check that the page looks ok
- Check the copy matches the copy doc

Copy doc: https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit?pli=1

### CODE REVIEW

**Comment by anthonydillon** [comment]
[Update /download/server/thank-you for landscape-self-service](https://trello.com/c/tRYa0yw8/2989-update-download-server-thank-you-for-landscape-self-service)

**Comment by barrymcgee** [comment]
The h1 in the copy doc says "Thank you", not "Thanks"

**Comment by barrymcgee** [comment]
"Your next steps with Ubuntu Server" section in copy doc is missing?

**Comment by barrymcgee** [comment]
'Learn more about Ubuntu Advantage' goes to `/cloud/management`, not `/cloud/services` as per copy doc

**Comment by barrymcgee** [comment]
'Helping hands' block is missing from contextual footer

**Comment by barrymcgee** [comment]
The 'Thank you' item in the nav breadcrumbs links to a different thank you page

**Comment by barrymcgee** [comment]
Hero text has now bottom margin on small screens - https://cl.ly/1N1H0t202r2c

**Comment by barrymcgee** [comment]
'Learn more about Ubuntu Advantage ›' links to `/server/management`, not `/cloud/services`

**Comment by anthonydillon** [comment]
@barrymcgee thank you very much. Very good spots. All fixed and ready for another review.

**Comment by barrymcgee** [comment]
LGTM! :shipit:

**Pull request merged**
