### PR TITLE
update news section on /cloud

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* removed old news/events section
* added homepage like news strip with news and possible spotlight (not event like in copy doc)
* if we want events, we would need to add that to insights, I think a spotlight like thing is good enough
* removed cloud section stylesheet

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/)
- compare to the [copy doc](https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit)

## Screenshots

image

### CODE REVIEW

**Comment by yaili** [comment]
Can you add a medium and a small screen screenshot, pls?

**Comment by anthonydillon** [comment]
Medium:
the leading operating system for pcs iot devices servers and the cloud - ubuntu 1

Small:
the leading operating system for pcs iot devices servers and the cloud - ubuntu 2

**Comment by WillMoggridge** [comment]
Automaticly updating demo is here:
http://www.ubuntu.com-pr-1985.run.demo.haus

**Comment by spencerbygraves** [comment]
On small screen the margin bottom on the link and the date is the same, which makes it hard to see which link the date is related too. Can we reduce the margin on the link for small screen?

image

**Comment by pmahnke** [comment]
@spencerbygraves you saw these.... can you +1?

@anthonydillon can you relook at the code? I made an include

## Done

* moved the news strip to be an include as it is now on both the homepage and cloud overview
* lessened the bottom margin on the headline on large and small.


## QA 

- look at [cloud overview](http://0.0.0.0:8001/cloud) and [homepage](http://0.0.0.0:8001/]

**Comment by pmahnke** [comment]
L
image
S
image

**Pull request merged**
