### PR TITLE
Created /security/certifications page

### LINKED ISSUE #4894: Create /security/certifications page
This is an epic for the **Create /security/certifications page** project

[brief](https://docs.google.com/document/d/137qy4LsYcUYIb1WpE3YwAc6QGQAq7HVGVHovOqRn3VI/edit)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Created /security/certifications page
- Updated [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/security/certifications](http://0.0.0.0:8001/security/certifications)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Compare to the copy doc
- still needs logos and design help

## Issue / Card

Fixes #4894

### CODE REVIEW

**Comment by anasereijo** [comment]
@pmahnke 

- [ ] hero section with white background and then alternate with light grey

- [ ] FIPS 140-2 and Common Criteria are part of the same thing or same section? If not, please have a different background colour for each one.

- [ ] can we hide all images on smaller screens? they are not very nice 

- [ ] space between Overview and Certifications is quite big on mobile version. I don't think this is our pattern or is it?

Screenshot 2019-04-09 at 10 23 06

**Comment by anthonydillon** [comment]
> FIPS 140-2 and Common Criteria are part of the same thing or same section? If not, please have a different background colour for each one.

These are different cert so deserve their own section.

> space between Overview and Certifications is quite big on mobile version. I don't think this is our pattern or is it?

Yes, this is are pattern. The links take up half the screen:
Screenshot_2019-04-09 OpenStack on Ubuntu is your scalable private cloud, by Canonical Ubuntu

**Comment by anthonydillon** [comment]
@anasereijo all changes applied.

**Comment by anasereijo** [comment]
@anthonydillon thanks

**Pull request merged**
