### PR TITLE
k8s install copy updates

### LINKED ISSUE #3449: Small changes from Carmine on the install - "Install Canonical Kubernetes" page - BUILD
copydoc: https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#heading=h.yb98vv47gv6p

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update copy on `/kubernetes/install` page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/install>
- See that the page matches the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#heading=h.yb98vv47gv6p)

## Issue / Card

Fixes #3449

### CODE REVIEW

**Comment by frankiegranato** [comment]
@steverydz  The ebook is not work as expected. Download does not appear to be working. If its tricky to do, I can suggest a simpler alternative. Please talk to me about this.

**Comment by steverydz** [comment]
@frankiegranato As discussed I've tried the card approach for the ebook download

**Comment by steverydz** [comment]
@anasereijo You might want to take a look at the download ebook section

**Comment by anasereijo** [comment]
@steverydz  looking good, just a small change
screen-shot-2018-06-26-at-17 23 54

**Pull request merged**
