### PR TITLE
Update cloud-eco landing page design

### PR DESCRIPTION
**Pull request by caldav**
## Done

- New design proposal

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)

### CODE REVIEW

**Comment by caldav** [comment]
This includes a rather ugly `style="margin-top:-1em;"`, let me know if you have another way to align the form with the text.

**Comment by anasereijo** [comment]
Hi @caldav just a few things

- we don't use background colours on pages (just on banners or smaller sections) but let's give it a try this time.
- please align vertically the logo with the form - it's looking unbalanced
- body copy is very big. can we please use our default styles? you can keep the first bit of copy this size (like we have on the homepage) but all the copy below that please make it 16px and headings 24px
see below a quick mockup
screencapture-ubuntu-pr-3328-run-demo-haus-engage-cloud-economics-2018-06-15-13_50_17

**Comment by caldav** [comment]
Is it better @anasereijo ? http://www.ubuntu.com-pr-3328.run.demo.haus/engage/cloud-economics

**Comment by anasereijo** [comment]
@caldav much better! thanks

**Pull request merged**
