### PR TITLE
Add new takeover to beta site

### PR DESCRIPTION
**Pull request by steverydz**
## Done

- Add new takeover
- Show old takeover after first session

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- See that the takeover matches the design
- Start a new session (e.g. open page in another tab) and you should see the old takeover

## Issue / Card

Fixes [#726](https://github.com/ubuntudesign/web-squad/issues/726)

### CODE REVIEW

**Comment by frankiegranato** [comment]
I just noticed the animation on load!!! Nice. +1

**Comment by anthonydillon** [comment]
Also seeing some issues on the homepage.
screenshot-2018-7-19 the leading operating system for pcs iot devices servers and the cloud ubuntu

**Comment by anasereijo** [comment]
@anthonydillon thanks for checking that!
just realised that the blog section is also looking different 

screen shot 2018-07-20 at 09 10 01

**Comment by steverydz** [comment]
@anthonydillon @anasereijo As these bugs aren't related to this PR (they're present on mongoose) I'll fix in a new ticket.

**Comment by steverydz** [comment]
@anthonydillon That heading issue is fixed in https://github.com/canonical-websites/www.ubuntu.com/pull/3772

**Comment by frankiegranato** [comment]
@steverydz can we please get this takeover live? I'll nudge some of the devs here to give you your reviews :-) Fyi @anthonydillon

**Pull request merged**
