### PR TITLE
Build the Tackling the IoT takeover

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Removed the session selecting JS. Replaced the existing two takeovers with the copy and design. Added a simple animation to the piggy bank. Changed the takeover styling to be inline so that we only need to simply change the include to see old takeovers.

**Do not merge**: 
1. Still awaiting a link for the whitepaper.
2. The right-side suru image provided does not match the design.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check that the copy matches [the copy doc](https://docs.google.com/document/d/1gcvBmsTPoJFdLB4p8A92tbjWVHQEYQOlZugFrBBYnek/edit#heading=h.meo0azuz09li)
- Check that it matches [the design](https://github.com/canonical-websites/www.ubuntu.com/issues/3892#issuecomment-414363647)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3894

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @anthonydillon,

As discussed can you please try other animation? Let me know if you need any help with this.

Please replace the right-hand side suru with this one: https://assets.ubuntu.com/v1/d3b283b9-suru-right-side.svg

thanks

**Comment by anthonydillon** [comment]
@anasereijo done

**Comment by frankiegranato** [comment]
I've discussed this with @anasereijo. This takeover is looking lovely but I think the animation is not quite right yet. Maybe just one coin drops on loading or maybe only one coin drops per minute ... ? ... I'll let Ana work it out with you @anthonydillon

**Comment by anthonydillon** [comment]
@frankiegranato do you happen to have the whitepaper for this?

**Comment by anthonydillon** [comment]
@anasereijo made all the changes apart from the mask. I have sped up the animation so it is difficult to see.

**Comment by anthonydillon** [comment]
@frankiegranato still waiting on the whitepaper

**Comment by anthonydillon** [comment]
Blocked on https://github.com/canonical-websites/www.ubuntu.com/pull/3914

**Comment by frankiegranato** [comment]
@anthonydillon This takeover should alternate, per session, between this one (1st) and the "Artificial intelligence, machine learning and Ubuntu" one (2nd)

**Comment by deadlight** [comment]
@anthonydillon I get an error trying to run the site:
```
2018-08-24 08:33:26.253Z INFO talisker.sentry.TaliskerSentryClient "Raven is not configured (logging is disabled). Please see the documentation for more information."
```

**Pull request merged**
