### PR TITLE
Add basic modal contact us on core page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add basic modal contact us on core page

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to /core
- Open the console and enter `dynamicContactUs();`
- Click any of the contact buttons and see the modal is displayed
- Click through the modal and check it goes back and forward
- Once complete check the Network tab has a form submission
- Check the contents of the request is correct

### CODE REVIEW

**Comment by anasereijo** [comment]
@anthonydillon [Designs](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/173) are ready. Can you please update this?

@Greggless suggested to make all pages the same size. Is that possible? 

Any questions let me know.

Thanks

**Comment by anthonydillon** [comment]
@anasereijo @Greggless I've updated the modal to match the design/copy doc. Could you have another look and let me know. I set the height of the modal but it caused large gaps on some panels. I have removed it.

**Comment by Greggless** [comment]
Thanks for the [designs](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/173) @anasereijo and the quick work @anthonydillon 

The format has now been signed off by stakeholders. The final form can be viewed in the [copy doc](https://docs.google.com/document/d/1StvJGPTI4zZ6srSTkR50JVjQY0_vulKE3BA8gVjXfBo/edit#).

## some issues
- [ ] 'What sectors...' question should use a paragraph field _only_, no checkboxes required
- [ ] 'What device...' and 'what platform...' questions should use checkboxes, not radio buttons
- [ ] 'What platform...' 'other' option should be a checkbox, when selected it should invoke a text field, in focus, with the cursor in it ready to type away
- **'Next' CTA** has tested poorly for discoverability, can we use
  - [ ] a #cdcdcd border around it
  - [ ] H5 text
  - [ ] a #f7f7f7 background all the time, with a #cdcdcd on hover
  - [ ] remove 'Previous' word and use just a chevron
- **[Let's discuss]** CTA should:
  - [ ] be in the same position as the 'Next' button.
  - [ ] be in a disabled state until the correct data has been supplied
  - This is not Vanilla, but it makes the form's behaviour better (IMHO)

**Comment by pmahnke** [comment]
@anthonydillon I didn't get the form to submit on the marketo side... how can we see what is submitted? I don't see anything in the inspector.

**Comment by anthonydillon** [comment]
@pmahnke do you see a post in the network tab? If so, it will contain the field data posted. I need to check Chrome though.

**Comment by pmahnke** [comment]
@anthonydillon 	definately didn't work on chrome.

> {error: true, errorCode: 400, message: "{leadCapture/save2} Approved form not found: "}
> error: true
> errorCode: 400
> message: "{leadCapture/save2} Approved form not found: "

that error might have even been before I hit submit.

**Pull request merged**
