### PR TITLE
Installed the packaged version of the global-nav

### LINKED ISSUE #4077: Remove bespoke global nav and replace with npm package

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Removed the local global nav assets and installed the packaged global-nav.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check that the global navigation loads and works correctly
- Check on small screens
- Check it doesn't break any links in and around other pages
- Check there are no JS errors in the console.

## Issue / Card
Fixes #4077

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @anthonydillon 

can you please fix the width? please match with what we have online now. 

_demo_
screen shot 2018-09-26 at 14 02 49


_live version (**what should look like**)_
screen shot 2018-09-26 at 14 03 27

**Comment by anthonydillon** [comment]
@anasereijo does it have to match live on Ubuntu.com? This would require a change and new release of the global navigation which was designed and signed off as it is. Is not a width issue, Ubuntu.com just has different padding then the package.

**Comment by anthonydillon** [comment]
@anasereijo done

**Comment by anasereijo** [comment]
@anthonydillon perfect! 🥇

**Pull request merged**
