### PR TITLE
VMWare-to-openstack landing page v0

### PR DESCRIPTION
**Pull request by caldav**
## Done

A first landing page example hosted on ubuntu.com

- [Copydoc](https://docs.google.com/document/d/1Wt8fkmkTbWJowrujNwsMna8SwHr24VUnPB0GM7sxGco/edit)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/engage](http://0.0.0.0:8001/engage)
- Ensure it redirects to `/resources`
- View the site locally in your web browser at: [http://0.0.0.0:8001/engage/vmware-to-openstack](http://0.0.0.0:8001/engage/vmware-to-openstack)
- Ensure the landing page is displayed correctly (signed in and out of Brighttalk)

## Screenshots

ef50bc31-cc9d-4511-b61c-880f7a2f653b

### CODE REVIEW

**Comment by frankiegranato** [comment]
Please try to remove the extra text surrounding the video. The play button is incorporated in the cover so we don't need another one. See my screenshot. 
edit from vmware to canonical openstack ubuntu

**Comment by anasereijo** [comment]
Hi,

just a few little things:

**"Your flexible cloud"**
we don't use bold on lists so maybe we can try something like this to make topics standout a bit more:
screen shot 2018-05-23 at 10 19 03

**"Built by the cloud experts"**
maybe this section can be a "p-strip--light is-deep" so it breaks the white background
screen shot 2018-05-23 at 10 34 23

We usually have the muted heading centred: "p-muted-heading u-align--center" (eg. bellow)
screen shot 2018-05-23 at 10 29 36

**Video section** the title should be a h2

**Aubergine section** the tile should be a h2 and remove the full stop. the button should have a 1.5rem top margin

Any questions let me know :) thanks

**Comment by frankiegranato** [comment]
Hi David, I see that you and Ana are making refinements to the landing page and it is looking really nice. One question - have you considered a "Contact us" CTA at the top of the page?

**Comment by caldav** [comment]
@anasereijo can I get your feedback on [this version](https://user-images.githubusercontent.com/18480003/40482226-59231d28-5f54-11e8-97db-ca98884ccd9d.png)

@frankiegranato James is reaching out to Brighttalk to see what can be done about simplifying the player

**Comment by anasereijo** [comment]
Hi @caldav it's already looking much better, thanks!

just some final small changes and then I think it's ready to go:

**hero banner**
- can you please make sure the headings are always sentence case? (remove the capital T)

**Built by the cloud section**
- add a bottom border to that banner
- I know you suggested to have an illustration and I agree it could look nicer but at the moment we can't use pictograms

**video section** please remove colon from the heading

Any questions let me know :)

Thanks

**Comment by anasereijo** [comment]
Hi @caldav where can we see the demo? thank you

**Comment by anasereijo** [comment]
@caldav ignore my previous comment, I just found it :) is looking nice thanks

**Comment by pmahnke** [comment]
giving it a UX +1

**Pull request merged**
