### PR TITLE
18.10 webinar created

### PR DESCRIPTION
**Pull request by inuwa**
## Done

Created 18.10 takeover according to [copy doc](https://drive.google.com/file/d/0B5Jc5K2-I_6xS1E4OWMwd0VNSkx5elJJZWpFMkdEUXhNQk5z/view)
## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check the [design spec](https://github.com/ubuntudesign/design.ubuntu.com-design/issues/15)  and the [copy doc](https://drive.google.com/file/d/0B5Jc5K2-I_6xS1E4OWMwd0VNSkx5elJJZWpFMkdEUXhNQk5z/view) refresh the page until the takeover for 18.10 webinar loads. Make sure that it matches the design documents.

## Issue / Card

Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4284
## Screenshots

image

image

### CODE REVIEW

**Comment by inuwa** [comment]
Hi @anasereijo the changes you requested have been effected. Some of the issues though have not been replicated. Probably were there before my last commit. Hopefully it is fine now. Cheers

**Comment by anasereijo** [comment]
Hi @inuwa,

The desktop version is looking fine now.
The copy is gone on smaller screens. see examples below:

screenshot 2018-10-30 at 09 41 46
screenshot 2018-10-30 at 09 41 57

**Comment by inuwa** [comment]
@anasereijo I have made the corrections you asked for. Cheers.

**Comment by inuwa** [comment]
@anasereijo change has been effected.✌️

**Comment by inuwa** [comment]
Superceded by https://github.com/canonical-websites/www.ubuntu.com/pull/4321

**Pull request closed without merging**
