### PR TITLE
update /download/desktop/contribute to vbt

### LINKED ISSUE #1629: /download/desktop/contribute/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /download/desktop/contribute to vbt
* I know the button text is white... that's been fixed in several other PRs

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/desktop/contribute?version=16.04.2&architecture=amd64)
* compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory&preview=download-contribute.png&qsid=21830873026803084826401499240920&query=containers) and the [demo](http://www.ubuntu.com-1629-download-desktop-contribute.demo.haus/download/desktop/contribute?version=16.04.2&architecture=amd64)

## Issue / Card

Fixes #1629

### CODE REVIEW

**Comment by yaili** [comment]
- [ ] Can we make the margin bottom in the section h5 headings 0.5rem?
- [ ] Can we remove the margin bottom in the section paragraphs?
- [ ] The button text should be white
- [ ] Can we make the contribute__total-currency and contribute__total-amount into p-heading--four?
- [ ] Below 768px the highlight card doesn't have enough padding, the PayPal button is too close to edge

**Comment by pmahnke** [comment]
@yaili fixed, except the button text, which is fixed in other PRs

**Comment by yaili** [comment]
- [ ] The p-heading--four was only for those two items, not the whole bottom row… now everything is HUGE

**Comment by pmahnke** [comment]
@yaili fixed... there was an unclosed tag on that that I missed... in live too ;-(

**Comment by barrymcgee** [comment]
@pmahnke I'd recommend this Atom linting package for flagging unclosed tags https://atom.io/packages/linter-htmlhint

**Pull request merged**
