### PR TITLE
New LP for 18.10 webinar

### PR DESCRIPTION
**Pull request by Khutch25**
## Done

Created a new landing page for the 18.10 webinar. Assumed the takeover image for this webinar is the same as the main 18.10 takeover image - _1810-takeover.html is the template I referred to for the hero image.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)

### CODE REVIEW

**Comment by shivjoshi1996** [comment]
This will use the takeover image that has been designed here https://app.zenhub.com/workspace/o/ubuntudesign/design.ubuntu.com-design/issues/15

(Still to be built)

**Comment by Khutch25** [comment]
> This will use the takeover image that has been designed here https://app.zenhub.com/workspace/o/ubuntudesign/design.ubuntu.com-design/issues/15
> 
> (Still to be built)

@shivjoshi1996

**Comment by anasereijo** [comment]
Hi @Khutch25,

The hero section looks very similar to a homepage Takeover and I think people might not notice they moved to a new page. @caldav and I talked about this some weeks ago and we decided to make the LPs hero sections less deep so we can have the content above the fold. Please check [this example](https://www.ubuntu.com/engage/evolving-software?utm_source=takeover&utm_medium=FY19_Cloud_Juju_Whitepaper) - it's a good example and you can use as a template. :)

As @shivjoshi1996 suggested please use the same background as the takeover. In this case I suggest not using the cuttlefish as it will make the section much deeper.

Any questions let me know 👍

**Comment by anasereijo** [comment]
Looking great @Khutch25 👍 

just 1 tiny thing and it's ready from my side:
can we make the hero section copy `class="col-7"`? That way the title can be in just 1 line :)

thanks!

**Comment by spencerbygraves** [comment]
Reviewing this as @anasereijo is ill today. Please can "Join Canonical product managers for a live panel discussion on the new features in Ubuntu 18.10" be h4 to match the takeover design.

Thanks.

**Comment by Khutch25** [comment]
> Reviewing this as @anasereijo is ill today. Please can "Join Canonical product managers for a live panel discussion on the new features in Ubuntu 18.10" be h4 to match the takeover design.
> 
> Thanks.

ahh yes, thank you @spencerbygraves! That has been updated to h4.

**Comment by spencerbygraves** [comment]
Great, thanks @Khutch25

**Pull request merged**
