### PR TITLE
Update features page

### LINKED ISSUE #2893: Update /desktop/features - build
Copydoc: https://drive.google.com/open?id=1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update desktop features page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/desktop/features>
- Make sure page matches [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit)

## Issue / Card

Fixes #2893

### CODE REVIEW

**Comment by frankiegranato** [comment]
Looking great @steverydz . Just a couple of small issues:

- [ ] Please double check that all the "A whole world of apps" texts match the copydoc (I notice that Slack and Skype do not). 

- [ ] Please ensure the contextual footer content matches the copydoc.

**Comment by steverydz** [comment]
@frankiegranato Changes made

**Comment by frankiegranato** [comment]
@steverydz just one small typo to remove (sorry I should have spotted it first time round). See note in the copydoc.

**Comment by steverydz** [comment]
@frankiegranato Fixed

**Comment by frankiegranato** [comment]
Thank you @steverydz!

**Pull request merged**
