### PR TITLE
Remove mobile from homepage

### PR DESCRIPTION
**Pull request by deadlight**
## Done

 - Removed mobile row from homepage
 - Removed mobile icon and associated styling from signpost

## QA

view the homepage in-browser.

[Demo](http://www.ubuntu.com-remove-mobile-from-homepage.demo.haus/)

### CODE REVIEW

**Comment by barrymcgee** [comment]
@yaili - is it ok for both of the row images to be on the right? Illustration: https://cl.ly/0343361H1E0e

**Comment by yaili** [comment]
@barrymcgee no, I think Juju should moved to the left.

**Comment by anthonydillon** [comment]
Looks good to me but would need a designer to check it.

**Comment by joanasa89** [comment]
Can we move the 'openstack' copy to the right? Maybe  "class="four-col prepend-**eight**"

**Comment by anthonydillon** [comment]
Graham is following this one with a fix.

**Pull request merged**
