### PR TITLE
Fix global nav 'more' dropdown

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Fixed the 'more' dropdown on the global nav.

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Drop down the 'more' menu in the global nav and see that it no longer has a large gap.

### CODE REVIEW

**Comment by anthonydillon** [comment]
Needs a demo link.

**Comment by barrymcgee** [comment]
@WillMoggridge Tried to build a demo for this feature branch but it failed? https://jenkins.demo.haus/job/demo/14215/console

**Comment by anthonydillon** [comment]
Demos are down at the moment.

**Comment by barrymcgee** [comment]
Demo: http://www.ubuntu.com-global-more-fix.demo.haus

**Pull request merged**
