### PR TITLE
Enterprise menu update

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the content of the enterprise menu to match the copy doc. Added source-maps to help find where styles are. Set the display to block on small screens to fix an FF quirk,

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Click the enterprise menu
- Check that it matches the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#)
- If you want, inspect an element and see where the styles come from.

## Issue / Card
Fixes https://github.com/ubuntudesign/web-squad/issues/666

### CODE REVIEW

**Comment by anasereijo** [comment]
hey @anthonydillon 

Desktop:
- can you please remove the summary?
- AI icon is not placed correctly:


Mobile:
- can we have some space between each section on "sectors"?  now it's looking quite busy (see below)

**Comment by anthonydillon** [comment]
@anasereijo done and ready for another look

**Comment by anasereijo** [comment]
@anthonydillon 

- mobile is looking the same to me. did you change anything?

- can you please match the top and bottom margins? I think the bottom one is 32px so can we have the same for the top one?

screen shot 2018-06-20 at 10 23 32

**Comment by anthonydillon** [comment]
@anasereijo The mobile should now have even padding:
screenshot-2018-6-20 the leading operating system for pcs iot devices servers and the cloud ubuntu

**Comment by anthonydillon** [comment]
@anasereijo updated the vertical padding in the menu.

**Comment by frankiegranato** [comment]
- [ ] I think @anasereijo Ana should consider aligning all the green cta buttons. Just a thought. 

This is just a memo to us all: we should keep our eye on the Nvidia page. I suspect it won't get built in time for launch, and in that case, we should remember to remove it from the menu.

**Comment by anasereijo** [comment]
@frankiegranato we talked about this yesterday with Spencer and we decided that although it would look nicer it's not the best option because it's hard to control if we add/remove copy. Unless we decide to have a word count to keep it the same?

**Comment by anasereijo** [comment]
@anthonydillon not sure what happened but just noticed the Headings (and copy) are not aligned:
get ubuntu download ubuntu

**Pull request merged**
