### PR TITLE
1601 containers overview

### LINKED ISSUE #1601: /containers to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /containers for vbt 

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/containers)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/4.%20Containers?preview=containers-overview.png) and the [demo](http://www.ubuntu.com-1601-containers-overview.demo.haus/containers)

## Issue / Card

Fixes #1601

### CODE REVIEW

**Comment by yaili** [comment]
Design review:
- [ ] Remove dotted border above contextual footer border
- [ ] Remove hero bottom border
- [ ] In the contextual footer, there should be padding bottom in the "Juju for container management" at S screen

**Comment by barrymcgee** [comment]
@pmahnke There's more than one page being changed here, not sure if it's deliberate but we should try to avoid this if possible, especially with multiple PRs in progress.. only a matter of time before one PR will merge and regress QA feedback in another.

**Comment by pmahnke** [comment]
@yaili fixed

@barrymcgee I agree... but it stops me from having to redo some files again and again... perhaps I will do that first next section

**Comment by yaili** [comment]
- [ ] Sorry, I just noticed that the hero is not aligned left with the edge of the grid (doesn't align with nav items above for instance) - compare with live https://www.ubuntu.com/containers

**Comment by pmahnke** [comment]
@yaili I got my suffix and prefix mixed.. but I think this looks better... hiddden in small, float left, 7 col for text

**Pull request merged**
