### PR TITLE
updating autopilot image on /cloud/openstack page

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* updated the autopilot row to make the image look better in large and medium viewports

## QA

1. go to /cloud/openstack
2. look at the autopilot row in medium and large

## Screenshots

Medium

image

Large

image

### CODE REVIEW

**Comment by joanasa89** [comment]
Think this pattern should be reviewed and make it consistent across the website.
Should I create a new issue ?

**Comment by pmahnke** [comment]
@joanasa89 I think this will be solved with the .u-image-position work on the vanilla brochure theme... I was tempted to even add it to ubuntu now... @anthonydillon and @yaili  what do you think?

**Comment by pmahnke** [comment]
I should say, I think there is still a potential issue on very large monitors

**Comment by anthonydillon** [comment]
You could pull over the image-position stuff from vanilla and kick the
tyres with it. If there are any more issues please file them in vanilla.

**Comment by pmahnke** [comment]
demo - http://www.ubuntu.com-cloud-openstack-image.demo.haus/cloud/openstack

**Pull request merged**
