### PR TITLE
Smarter navigation

### PR DESCRIPTION
**Pull request by nottrobin**
Replace the existing, somewhat confusing `level_1` etc. navigation system with a new one:

- A `navigation.yaml` defines the navigation sections, and the hierarchy of children within each
- The breadcrumb navigation will be displayed according to this hierarchy
- The main navigation in the header will display the sections in `navigation.yaml` that have `include_in_menu: True`
- Individual pages can override the default breadcrumbs etc. by using the new `header` block
  - I've used this so far only in `cloud/contact-us.html` and `cloud/thank-you.html`

## QA

`./run`

Browse to <http://0.0.0.0:8001/cloud>, for example. Click around and check everything looks accurate. Check navigation in header, breadcrumbs and footer See <http://0.0.0.0:8001/cloud/contact-us> and <http://0.0.0.0:8001/cloud/thank-you> as well.

### CODE REVIEW

**Comment by pmahnke** [comment]
@nottrobin amazing... I don't see /cloud/thank-you or contact-us having overwritten nav... but the rest looks good (locally) the demo seems broken...

do you want to check this?

so happy

**Comment by nottrobin** [comment]
@pmahnke demo works for me. overwritten nav i s here: https://github.com/canonical-websites/www.ubuntu.com/pull/1897/files#diff-af4d4c1ef87e1dc4ab1155cfb33757a3R5

**Comment by anthonydillon** [comment]
Seems the contract pages have no nav on small screens.

http://www.ubuntu.com-pr-1897.run.demo.haus/desktop/contact-us

**Comment by anthonydillon** [comment]
Navigation does not work on the search results page on a phone. Might be
the failed connection.

http://www.ubuntu.com-pr-1897.run.demo.haus/search?q=Hello

**Comment by anthonydillon** [comment]
Missing breadcrumbs in the download section.
http://www.ubuntu.com-pr-1897.run.demo.haus/download/desktop

**Comment by nottrobin** [comment]
@anthonydillon :

> Seems the contract pages have no nav on small screens.

They had no nav at all. It's 'cos I only bothered to sort out the cloud one properly. I've now set up all the contact-us and thank-you pages properly.

> Navigation does not work on the search results page on a phone. Might be
the failed connection.

This is nothing to do with the failed connection. I've fixed it.

> Missing breadcrumbs in the download section.

This is not to do with my work - it's the `v1` layout stuff. I haven't touched the `v1` stuff for now. It's a pre-existing issue that's also in master.

**Comment by pmahnke** [comment]
@nottrobin you are missing the scenerio that messed up my template version too

in second nav, like location like /download/ubuntu-kylin, you should see the same as /download because ubuntu-kylin has no children... and ubuntu-kylin should be 'active'

yours
image

live
image

so you need to loop around the second level in that case... here:

```
                  <ul class="second-level-nav">
                    <li class="p-breadcrumbs__item"><a class="p-breadcrumbs__link {% if page.url_path == page_path %}is-active{% endif %}" href="{{ page_path }}">{{ page_title }}</a></li>
                  </ul>
```
also, the is-active logic doesn't seem to work everywhere? (like in this example)

**Comment by yaili** [comment]
Should I wait to do a design review once the issues are fixed?

**Comment by nottrobin** [comment]
@pmahnke I see what you're saying. Yes I hadn't understood that requirement. It's not too difficult to solve though.

**Comment by nottrobin** [comment]
@pmahnke The top nav, breadcrumb nav and footer navs should now behave exactly as on live, on pages which use the `base.html` base template.

None of these changes will currently effect pages using the `base-v1.html` base template.

**Comment by yaili** [comment]
- When I visit /cloud the breadcrumb is not in the right position
screen shot 2017-06-05 at 11 39 48

- When I visit /downloads or /about there is no breadcrumb
screen shot 2017-06-05 at 11 39 38

Is there another place I should be looking at?

**Comment by nottrobin** [comment]
@yaili `/download` etc. are based on a new template for the new v1 work, which I am not touching in this PR. After this PR is merged, someone can go through and update the v1 template in the same way as I have done for `/core` etc.

I also haven't broken anything in those new templates - what you're seeing on `/download` is the existing state of `master`. If this is a bug, it should be fixed in a separate PR.

**Comment by nottrobin** [comment]
@pmahnke I've now updated that demo, so you should see the correct navigation behaviour in http://www.ubuntu.com-pr-1897.run.demo.haus/cloud

**Comment by pmahnke** [comment]
@nottrobin looks ok, except thank-you and contact-us have no nav still

**Comment by nottrobin** [comment]
@pmahnke *sigh* oh alright then I suppose I'll fix them

**Comment by nottrobin** [comment]
Closing. Superseded by #1942 and #1943.

**Pull request closed without merging**
