### PR TITLE
Remove self-service livepatch feature from /support

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Remove self-service livepatch feature from /support

## QA
- Pull code and run `./run`
- Go to http://0.0.0.0:8001/support
- Check that the page looks ok
- Check the comments are complete in the copy doc

Copy doc: https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit?pli=1#

### CODE REVIEW

**Comment by anthonydillon** [comment]
[Remove livepatch self-service feature from support](https://trello.com/c/BxaBrhiP/3101-remove-livepatch-self-service-feature-from-support)

**Comment by barrymcgee** [comment]
The list is in a different order than the copy doc, not sure if it matters?

**Comment by joanasa89** [comment]
@anthonydillon 
- The t&t logo is squashed. Can you fix that?
- Why is the logos section after 'why ubuntu advantage?' section and not after 'system management tool' ?

**Comment by anthonydillon** [comment]
The at&t logo is a broken logo image which has been there for some time. Let's fix that one after this.

**Pull request merged**
