### PR TITLE
lp - multi-cloud guide

### PR DESCRIPTION
**Pull request by caldav**
## Done

* New landing page at `/engage/multi-cloud-guide`
* [copy doc ](https://docs.google.com/document/d/1fjt7cKzopJk6GPWKNQiUU3fv9p4yZ1OCcVUW1_Q2NrU/edit#)

## TODO

* [x]  ~**Update form ID when available**~
* [x]  ~**Update form return URL when available**~
* [x] Update hero with takeover design

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Ensure the page looks good and matches the copy doc
- Ensure the form takes you to the right thank you page

### CODE REVIEW

**Comment by anasereijo** [comment]
@caldav 

- can you make the sub title "What is the right cloud strategy for your business?" an `h3`?
- see more changes on this image:
cio guide to multi cloud operations ubuntu

- as Frankie said, once the takeover is ready please use it for the hero section too.  In the meantime if you want to see the design you can check it [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/153)

**Comment by caldav** [comment]
@anasereijo sounds good, with one comment: 

The list of clouds is something readers are trying to make a choice from and the goal of this whitepaper is to provide a guide to pick a single item from this list. 

With every item ticked, I think it becomes confusing, because it's exactly the opposite of what they are looking for: guidance for ticking a single item on this list. If we need bullets for this list, my choice would probably be something like empty tick circles.

**Comment by anasereijo** [comment]
Hi @caldav thanks for your comment, I totally agree with you. Keep them without the ticked icon :)

thanks

**Comment by caldav** [comment]
@anasereijo updated

**Comment by anasereijo** [comment]
@caldav looking good! but now that we don't have the ticked icon maybe we need to have the dividers again: `p-list--divided is-split` to look more like a list

**Comment by caldav** [comment]
@anasereijo agreed, just changed it 

screenshot-20180904111103-1100x928

**Comment by anasereijo** [comment]
@caldav cool 👍 I will +1 once we have the hero section ready.

**Comment by frankiegranato** [comment]
@caldav I have suggested one small series of edits in the copy doc. Aside from that, its a +1 from me. Please go ahead and make my edit if you agree with it, but there's no need to wait for another +1 from me if the landing page needs to go-live before I'm back (I won't be back until Monday). Thanks.

**Comment by caldav** [comment]
@frankiegranato thank you, done! 

The form details have been added as well, removing _Don't merge_. Ready to merge when the takeover is in.

**Pull request merged**
