### PR TITLE
Whitepaper on the web

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Built the robotics whitepaper.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to /whitepapers/robotics
- Check that looks ok
- Check on small screens
- Check it matches [the whitepaper](https://drive.google.com/file/d/1pk8j0wuPsfwmaRSrTwaU8MTH_frFX2EV/view?usp=sharing)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4782

### CODE REVIEW

**Comment by anasereijo** [comment]
As discussed earlier I am designing a template and I will have it ready soon.
In the meantime, you can amend a few things on this version:

- [ ] delete canonical's logo

- [ ] `h1` should be vanilla's default colour: `#111111`

- [ ] some whitepapers will have a line or two of intro copy. Can you please add some placeholder for now? It should be below the title and 

- [ ] Date to be `p-small` (14px) and default colour `#111111`

- [ ] Introduction title to be `h3`

- [ ] All text should be default colour `#111111` and the highlighted `#772A54`

- [ ] Images should be `col-2`

- [ ] Text should be `col-6`

- [ ] Can you left align quotes with text? 

- [ ] No full-width images: make them match the grid width

**Comment by anthonydillon** [comment]
@anasereijo Addressed your points. I am not sure its better in places but let me know what you think.

**Comment by anasereijo** [comment]
- [ ] `h3` should be default colour

- [ ] `class="u-text--accent"` can we make the bullet purple to match the text?

- [ ] vertically align images. see below

Screenshot 2019-03-13 at 14 23 31

- [ ] can we amend the text grid? see below

Key considerations when choosing a robot’s operating system   Ubuntu

**Comment by anasereijo** [comment]
I think after those changes this will be a good first version. We can then iterate implementing my design/functionalities.

**Comment by pmahnke** [comment]
closing as this has been updated in anothe pr

**Pull request closed without merging**
