### PR TITLE
 New finserv month landing page 

### PR DESCRIPTION
**Pull request by caldav**
## Done

* New landing page for financial services month

## TODO before merging

- [x] UTMs
- [x] Copy doc: https://docs.google.com/document/d/1THWC0QzAzGOoaLXWrxil100SkpvXm3tJd9fUlwRZGzg/edit#heading=h.teujcix8oibf

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to http://0.0.0.0:8001/engage/financial-services-month and ensure the page looks good

### CODE REVIEW

**Comment by caldav** [comment]
(adding the don't merge label until UTMs are in)

**Comment by anasereijo** [comment]
Hi @caldav, I have some suggestions:
- [ ] Hero section: use the same design as the takeover (@Caleb-Ellis is going to build it soon)

- [ ] September 12 webinar: use [Canonical's logo](https://assets.ubuntu.com/v1/5d6da5c4-logo-canonical-aubergine.svg)

- [ ] September 19: delete illustration and move text to the left-hand side

- [ ] September 26: move illustration to left-hand side and make it bigger 

- [ ] "Don’t want to wait?": make the background light grey

any questions let me know :)

**Comment by frankiegranato** [comment]
@caldav Is there a copydoc I can suggest edits in?

**Comment by caldav** [comment]
@frankiegranato [copy doc](https://docs.google.com/document/d/1THWC0QzAzGOoaLXWrxil100SkpvXm3tJd9fUlwRZGzg/edit#)

**Comment by caldav** [comment]
@anasereijo updated, but I'm waiting for the takeover to land in this branch to update the hero (so I can inherit its CSS)

**Comment by anasereijo** [comment]
thanks for making the changes @caldav 👍 
I will give +1 once we have the hero updated. thanks

**Comment by caldav** [comment]
Still keeping *Don't Merge* until I have confirmation that the Marketo backend is connected to the campaigns

**Comment by frankiegranato** [comment]
@Caleb-Ellis & @caldav the takeover looks great. +1 from me.
However, I think the landing page needs work - the language is quite hard to penetrate in places. I'll make edits in the copy doc: https://docs.google.com/document/d/1THWC0QzAzGOoaLXWrxil100SkpvXm3tJd9fUlwRZGzg/edit#

**Comment by anasereijo** [comment]
@caldav the dates are looking quite big can you please make them `<h4 class="p-muted-heading">`

screen shot 2018-09-03 at 13 46 32

thank you

**Pull request merged**
