### PR TITLE
Build Kubernetes Month takeover

### LINKED ISSUE #2738: Build Takeover

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Build takeover for Kubernetes Month

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Check that takeover matches design from https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2738

## Issue / Card

[Fixes #2738](https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2738)

## Screenshots

the leading operating system for pcs iot devices servers and the cloud ubuntu 1
the leading operating system for pcs iot devices servers and the cloud ubuntu

### CODE REVIEW

**Comment by anasereijo** [comment]
@steverydz

Desktop
- can you move "enterprise." up?
- Kubernetes logo is looking big can you please make it 264x 257px
- as we discussed please replace the background with the amended one: https://assets.ubuntu.com/v1/06c85daf-FINAL+-+Takeover-large-screen.jpg

Any questions let me know :)

thank you

**Comment by anasereijo** [comment]
@steverydz here goes another background
https://assets.ubuntu.com/v1/14fba4f5-Takeover-large-screen-k8s.jpg
thank you

**Comment by anasereijo** [comment]
@steverydz https://assets.ubuntu.com/v1/94206a69-Takeover-large-screen-k8s.jpg

**Comment by anasereijo** [comment]
@steverydz hopefully this works :)
https://assets.ubuntu.com/v1/94206a69-Takeover-large-screen.jpg

**Comment by steverydz** [comment]
@anasereijo I've updated this and it seems to have done the trick:



The link won't be updated yet - I've asked for help getting the tool working but when it is you'll get a notification on this thread.

**Comment by anasereijo** [comment]
@steverydz looking much better! thank you
I will have a look again when the link is updated.

**Comment by steverydz** [comment]
@anasereijo I haven't been able to regenerate the page but for now you could view the page served from my computer at this link: http://172.17.0.1:8001/

**Comment by anasereijo** [comment]
@steverydz looks good to me.

**Comment by anasereijo** [comment]
@spencerbygraves you can see the takover here: http://www.ubuntu.com-pr-2831.run.demo.haus/

**Pull request merged**
