### PR TITLE
1604 containers docker ubuntu

### LINKED ISSUE #1604: /containers/docker-ubuntu to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* added testimonial pattern

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: 
[page](http://0.0.0.0:8001/containers/docker-ubuntu)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/4.%20Containers?preview=containers-docker-ubuntu.png) and the [demo](http://www.ubuntu.com-1604-containers-docker-ubuntu.demo.haus/containers/docker-ubuntu)

## Issue / Card

Fixes #1604

### CODE REVIEW

**Comment by yaili** [comment]
@pmahnke is this a Vanilla task, should have the milestone if so

**Comment by yaili** [comment]
- [ ] Can the "The no-nonsense" be strip deep?
- [ ] Missing the word Containers as first breadcrumb item
- [ ] Containers is also missing as the first item in S screen nav

**Comment by yaili** [comment]
@barrymcgee I don't see any changes made since my first review

**Comment by barrymcgee** [comment]
@yaili Yeah, sorry, accident - if you see the label activity above your comment I cancelled the request but I guess the email was already pinged off to you.

**Comment by pmahnke** [comment]
@yaili fixed

**Comment by yaili** [comment]
- [ ] This is also showing the bug where the first contextual footer doesn't have enough bottom padding at S screen, I don't remember this being there…

**Comment by pmahnke** [comment]
@yaili fixed... again

**Pull request merged**
