### PR TITLE
1609 cloud juju

### LINKED ISSUE #1609: /cloud/juju/ to VBT

### LINKED ISSUE #1888: broken charm/bundle links
I see a few broken and/or outdated links on:

https://www.ubuntu.com/cloud/juju

In the charm section:
- Hadoop should be replaced with Kafka (https://jujucharms.com/kafka/)
- Spark should link to https://jujucharms.com/spark/
- The DB2 charm has a poor UX (it's not deployable without attaching pre-purchased software).  I'd recommend removing this.

In the bundle section:
- apache-core-batch-processing should be replaced with hadoop-processing (https://jujucharms.com/hadoop-processing)
- apache-hadoop-spark should be replaced with spark-processing (https://jujucharms.com/spark-processing)

---
*Reported from: https://www.ubuntu.com/cloud/juju*

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /cloud/juju to vbt
* replaced 3 broken charms and a few broken bundles with new ones from this issue #1888
* pointed to JAAS beta

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/juju)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-juju.png)

## Issue / Card

Fixes #1609
Fixes #1888

### CODE REVIEW

**Comment by yaili** [comment]
@pmahnke this demo isn't working either, maybe I should wait a bit

**Comment by yaili** [comment]
Design review of localtunnel:
- [ ] Add border below "Juju at a glance"
- [ ] Can we add space above the CTA in "Juju at a glance"…
- [ ] … and an external link icon…
- [ ] … and make it "Read the docs: Getting started with Juju"?
- [ ] The cards in "Charms available for over 300 services" should align left with the rest of the content
- [ ] Do we ever say Juju-as-a-Service? Should we ask someone in Juju team? (re: last row)

**Comment by barrymcgee** [comment]
@pmahnke The youtube video here is huge on my widescreen - is it supposed to be full screen?

**Comment by pmahnke** [comment]
@barrymcgee the large video was because of an unclosed div

@yaili fixed up all issues and made the charms list flow, also changed the text to JAAS from as a service.

**Comment by yaili** [comment]
@pmahnke demo isn't working

**Comment by pmahnke** [comment]
@yaili demo - http://www.ubuntu.com-1609-cloud-juju.demo.haus/cloud/juju

**Pull request merged**
