### PR TITLE
2288 server page update

### LINKED ISSUE #2288: 17.10 updates to /server - overview
David Britton and others have made some edits for 17.10. See copydoc: https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Updated /server with 17.10 content as per [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4)

## QA

- Check that /server has been properly updated with 17.10 content.

## Issue / Card

Closes #2288

### CODE REVIEW

**Comment by frankiegranato** [comment]
@Caleb-Ellis Sorry about this: despite my UX+1, I just spotted a mistake in the copy, and I have requested that you make another edit before merging.

**Comment by kwm14** [comment]
## Visual review

Looking good just one minor change :)

### MAAS - bare metal provisioning
- update MAAS grey icon to orange icon - https://assets.ubuntu.com/v1/0de4fcd5-logo-maas-icon.svg

**Comment by Caleb-Ellis** [comment]
Should be good now. Updated the LTS bullet point and changed the MAAS icon to orange.

**Comment by kwm14** [comment]
Thanks @Caleb-Ellis looking good 👍

**Pull request merged**
