### PR TITLE
Add ITstrategen case study to /support

### LINKED ISSUE #2398: Add case study to /support-overview page
Please add case study to /support-overview page. 

Copydoc:https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#

Re design: Can we use the padlock and chain asset as seen on https://www.ubuntu.com/desktop/government please?

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Add new ITstrategen case study to /support overview page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
- Make sure the case study has been added [as per the copy doc](https://docs.google.com/a/canonical.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit?disco=AAAABa0-_v4)

## Issue / Card

Doc: https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#
Issue: https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2398

Fixes #2398

### CODE REVIEW

**Comment by grahambancroft** [comment]
Changed it to be a shared file as https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2396 needs the same case study

**Comment by frankiegranato** [comment]
Finn is napping so I can do a bit of work so: this is looking great @grahambancroft. But I have a few small requests: 1) can we make the link a button please? and 2) can we add a grey rule to divide the case study row from the community row below (I just think it might look neater). thanks.

**Comment by grahambancroft** [comment]
@frankiegranato Done and done

**Comment by frankiegranato** [comment]
We need an extendedised chain in that graphic!

**Comment by grahambancroft** [comment]
@frankiegranato New image added, ready for re review

**Comment by frankiegranato** [comment]
@spencerbygraves Michael has kindly re-drawn this chain and padlock graphic for us (we needed a longer length of chain to span the section). However, by using a redrawn padlock, I'm wondering if we are disregarding one of the "original" Ubuntu brand icons. Please can you review and feedback? thanks.

**Comment by frankiegranato** [comment]
On second thoughts, after talking to Michael about the origins of this icon (he got the padlock icon from an newer set of icons, and its featured in Joanna's takeover artwork), I think its fine to go with it. @spencerbygraves no need to review :-)

**Pull request merged**
