### PR TITLE
1577 search

### LINKED ISSUE #1577: /search to VBT

### LINKED ISSUE #1945: Search looks broken in master branch
I'm sure this will be fixed when someone implements #1577, but for the time being, search styling is broken in master, which is dangerous as presumably that means it might inadvertently go live:

search-broken

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* updated the search page to vanilla brochure theme
* changed the design slightly to reflect new theme

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- use your Canonical VPN
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/search?q=arm) note there are no 'next' or 'first' links
- test the [last page of search](http://0.0.0.0:8001/search?q=arm&limit=10&offset=300) see that it has messages and no 'next' link
- test the [second page](http://0.0.0.0:8001/search?q=arm&limit=10&offset=10) see that it has no 'Previous' link
- test a [middle page](http://0.0.0.0:8001/search?q=arm&limit=10&offset=20) see that it has all the links

## Issue / Card

Fixes #1577 
Fixes #1945

### CODE REVIEW

**Comment by yaili** [comment]
@pmahnke will there be a demo link?

**Comment by nottrobin** [comment]
@yaili Demo here: http://www.ubuntu.com-1577-search.demo.haus/search?q=ubuntu - but search will always time out and display an error on demo.haus. To properly see it you'll need someone to demo it for you specifically I'm afraid.

If you ping me when you're free in IRC I can set up a temporary demo from my machine.

**Comment by nottrobin** [comment]
@pmahnke The last page at http://0.0.0.0:8001/search?q=ubuntu&limit=10&offset=390 is still showing the "Last >>" link, back to itself. I don't think it should.

**Comment by nottrobin** [comment]
@pmahnke okay I fixed that for you, now this is code and QA +1 from me.

**Comment by pmahnke** [comment]
@nottrobin thanks... sadly I also fixed it... I will delete mine.

**Comment by nottrobin** [comment]
@yaili working demo available for a limited time only: https://ijtyemsalv.localtunnel.me/search?q=ubuntu

**Pull request merged**
