### PR TITLE
Update logo clouds to use links

### LINKED ISSUE #2769: Add links to partner sites in partners.u.c based logo clouds
## Summary

- Add links to partner sites in partners.u.c based logo clouds
- Fix aspect ratios on logos in cloud, they appear to be distorted

image

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update logo clouds to use links, if they exist
- Fix unconstrained image resizing with combo of max-width and max-height
- Filed an [issue to fix in Vanilla](https://github.com/vanilla-framework/vanilla-framework/issues/1605)
- update etisalat logo

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at:
  - http://0.0.0.0:8001/containers
  - http://0.0.0.0:8001/cloud/partners
  - http://0.0.0.0:8001/desktop/partners
  - http://0.0.0.0:8001/internet-of-things/gateways
  - http://0.0.0.0:8001/internet-of-things/robotics
  - http://0.0.0.0:8001/server/hyperscale
  - http://0.0.0.0:8001/server
- See that the logos have links
- See that the logos maintain their aspect ratio
- See that the logos do not get clipped on small screens

## Issue / Card

Fixes #2769

### CODE REVIEW

**Comment by pmahnke** [comment]
@Caleb-Ellis I just recreated this

**Comment by Caleb-Ellis** [comment]
I know you asked me to stop being thorough, so here's me not doing that at all. I've noticed these logos are broken (they might not show for you since it seems the partner logo feed changes every few minutes):
- /core
  - Raspberry Pi (https://assets.ubuntu.com/v1/31bd2627-logo-raspberry-pi.svg?w=200)
  - AWS (https://assets.ubuntu.com/v1/e9108036-amazon.svg)

- /cloud
  - Caringo (https://assets.ubuntu.com/v1/c0eaade5-Caringo.svg)

- /public-cloud
  - Rackspace (https://assets.ubuntu.com/v1/ff936628-rackspace.svg)

- /server
  - Supermicro (https://assets.ubuntu.com/v1/bb3de557-Supermicro_GreenC_NewLogo_WhiteBackground.svg)

- /server/hyperscale
  - Penguin Computing (https://assets.ubuntu.com/v1/88205456-penguin-computing-logo-outline-black.svg)

- /telecommunications
  - Telecom Infra Project (https://assets.ubuntu.com/v1/eeae998a-telecominfraproject-logo.svg)

There could be more, so I think it might be a good idea to come up with a fix that will work for SVGs that are given a default width and height of 0px.

**Comment by pmahnke** [comment]
@Caleb-Ellis I think I have a solution if you wouldn't mind looking again.

**Comment by Caleb-Ellis** [comment]
The PNGs are fixed and don't stretch anymore (Docker), but SVGs are stretched again (Kubernetes).

screenshot_2

**Comment by pmahnke** [comment]
@Caleb-Ellis again?

**Comment by Caleb-Ellis** [comment]
The 0px SVGs have disappeared again :(

screenshot_3

**Comment by pmahnke** [comment]
@Caleb-Ellis updated

**Comment by Caleb-Ellis** [comment]
lolollol

screenshot_4

**Comment by pmahnke** [comment]
@Caleb-Ellis can you look one more time?

**Comment by Caleb-Ellis** [comment]
It works! Amazing. Just needs a rebase with master and it should be good to go :+1:

**Comment by Caleb-Ellis** [comment]
@pmahnke Something weird has happened with the rebase. It's trying to merge commits that are already in the beta branch. Did you run `git rebase beta` on this branch?

**Comment by Caleb-Ellis** [comment]
@pmahnke Something weird has happened with the rebase (24 commits?!) but I think it's fine to just squash and merge.

**Pull request merged**
