### PR TITLE
update /download/cloud/conjure-up to vbt

### LINKED ISSUE #1624: /download/cloud/conjure-up to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /download/cloud/conjure-up to vbt
* added color fixes for p-strip--accent fieldset background and border

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/cloud/conjure-up)
- compare to the [autopilot design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/9.%20Download?preview=download-cloud-autopilot.png) and the [demo](http://www.ubuntu.com-1624-download-cloud-conjure-up.demo.haus/download/cloud/conjure-up)

## Issue / Card

Fixes #1624

### CODE REVIEW

**Comment by yaili** [comment]
Design review:
- [ ] Can you confirm if the padding of the input text fields is coming from Vanilla, because if they are they are not implemented according to spec (padding is the other way around)
- [ ] Can we make the text column in the "Before you start" section col-7 instead of col-6?
- [ ] The p around the image in "Before you start" I think also needs the u-align--center class
- [ ] There is something wrong about the second heading in the "Installation instructions" and it might be the Vanilla Brochure theme/Vanilla implementation of the pattern: there is some indentation which means the text doesn't align left and the line height of the heading is too high, does it make sense?
- [ ] Should "http://<openstack ip>/horizon " be in code tags?
- [ ] In S screen, the ebook form should be aligned left to the rest of the content, it's a bit indented

I've added two separate issues to the repo about some patterns across other pages that don't need to block this.

**Comment by pmahnke** [comment]
@yaili 

- input fields I submitted a PR
- updated the code blocks
- autopilot page will update the form issues
- instruction headings are a bug

**Comment by yaili** [comment]
- [ ] I don't see the second and third items changes, is that what you mean by "autopilot page will update the form issues"?

**Comment by pmahnke** [comment]
@yaili I think this is fixed

**Comment by yaili** [comment]
Getting an error with the demo link, 502 error

**Comment by barrymcgee** [comment]
@yaili Kicked the demo - http://www.ubuntu.com-1624-download-cloud-conjure-up.demo.haus/

**Comment by yaili** [comment]
@pmahnke I still see the same

**Comment by pmahnke** [comment]
@yaili 2 & 3 were fixed in /autopilot, but I fixed here too now...

**Comment by barrymcgee** [comment]
Field labels are white?

screen shot 2017-05-30 at 14 18 54

**Comment by barrymcgee** [comment]
Breacrumb nav looks wierd?

screen shot 2017-05-30 at 14 23 24

**Comment by pmahnke** [comment]
@barrymcgee the labels should be white, the fieldset should be $color-accent could the css not have built?

the demo looks fine

image

also, what should the nav look like?

is it missing chevrons?

this is live 

image

**Comment by barrymcgee** [comment]
@pmahnke Field labels look good now, might have been cache issue locally. Figured breadcrumb looks weird as there's only one sibling page to this page meaning it kinda floats on it's own out to the right. However, that's unrelated to this PR so all good.

**Comment by barrymcgee** [comment]
@pmahnke Fix conflicts and this is good to merge.

**Pull request merged**
