### PR TITLE
Beta nav animation test

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Animation demo for beta nav
  - Enterprise: Simple fade in
  - Developer: Fade in and a slight translate down
  - Community: Slide down
  - Download: Slide down with a fade in of content
- I personally like Developer the best - it's not as "busy" as the slide down ones or as boring as the fade-in, but there's still enough movement to make it seem snappy.
- Ignore the code. You'll be happier that way.

### CODE REVIEW

**Comment by kwm14** [comment]
@Caleb-Ellis I also like **_Developer_** transition. With the slight fade in are we using Vanilla's animation values?

**Comment by spencerbygraves** [comment]
@Caleb-Ellis @kwm14 I think the developer version could work, but I think it travels too far, and too slowly. Can we discuss some variations please?

**Comment by Caleb-Ellis** [comment]
@kwm14 Yeah it uses Vanilla's 'brisk' duration and the 'ease-out' timing function.
@spencerbygraves I've made the Developer dropdown slightly faster and move slightly less (1rem less). But I agree I feel like this should be discussed a bit more amongst the team before I do any more work on demos.

**Comment by frankiegranato** [comment]
All the new slide-down versions (ie. Developer, Community, Download) are a big improvement on the previous  version. As a user, it nice to receive a clear signal that a "temporary presentation of new information" has occurred :-)
I think I also slightly prefer the Developer version (with the fade in and a slight translate down), but I trust that you guys are exploring all options.

**Comment by frankiegranato** [comment]
@Caleb-Ellis lets make sure we pick this up when you are back in the office. Please remind me to have a huddle with you about it :-)
Fyi @kwm14 & @spencerbygraves @pmahnke

**Comment by Caleb-Ellis** [comment]
Agreed with @kwm14 and @spencerbygraves to go ahead with 'Developer' style transition: snappy fade in and translate down. Closing this PR and will reopen with animation applied to all tabs.

**Pull request closed without merging**
