### PR TITLE
Remove edubuntu flavour from alternative flavours

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Remove edubuntu flavour from alternative flavours

## QA

- Pull code and run ./run
- Go to http://localhost:8001/download/ubuntu-flavours
- Check that edubuntu has been removed and that the list is now in alphabetical order

The will get design sign off on 1704-dev

## Issue / Card

Card: https://trello.com/c/XgvM9qly

### CODE REVIEW

**Comment by grahambancroft** [comment]
[Remove edubuntu flavour from alternative flavours](https://trello.com/c/XgvM9qly/3091-remove-edubuntu-flavour-from-alternative-flavours)

**Comment by barrymcgee** [comment]
screen shot 2017-04-11 at 15 28 26

**Comment by grahambancroft** [comment]
@barrymcgee this seems to be an vanilla pattern issue that is apparent on live also. Would you be happy to approve this change and I’ll add an issue for the pattern?

**Comment by barrymcgee** [comment]
@grahambancroft This issue will resolve itself in Vanilla v1 migration so no need to add an issue. As unrelated to core changes here, I'm happy to approve and merge.

**Pull request merged**
