### PR TITLE
SEO updates to the /esm page

### LINKED ISSUE #4716: ESM page SEO update - Build

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Updated the text per the [copy doc]()
- Merged in the FAQ page
- Redirected the FAQ link to the /esm#faq
- Added a sticky nav
- Tweaked the CTA (which likely needs more design help @anasereijo)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/esm](http://0.0.0.0:8001/esm)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- [List additional steps to QA the new features or prove the bug has been resolved]

## Issue / Card

Fixes #4716

### CODE REVIEW

**Comment by anasereijo** [comment]
- [ ] if you scroll down the page the sticky nav links don't change to active -> add `class="p-tabs__link js-sticky-tab is-selected"`

- [ ] there is too much space between "Frequently asked questions (FAQ)" intro copy and the 1st question. I think it's because they are in seperate `sections`?

- [ ] can we have a `</br>` here: 
"Yes, in quantities of 1,000 machines or above, at $50/node/year. `</br>`Contact Canonical Sales."

I am designing a solution for the CTA. I will add a new comment once that's ready.

**Comment by anasereijo** [comment]
@anthonydillon looking perfect! I will give a +1 once all is done. I will upload the new CTA here too.

**Comment by anasereijo** [comment]
**New CTA design:**

esm

**grid view:**

screenshot 2019-02-18 at 16 58 03

- icon: `class="col-1 u-align--center u-vertically-center u-hide--small"`

- please keep gutter between icon and text (at the moment is too close to the text)

- 'Any questions?' should be `<h4>`

- 'Call us +1 737 204 0291 (Americas), +44 203 656 5291 (RoW) or ' should be `<p>`

- 'contact us online' button should be `<button class="p-button--base"> `

**Comment by caldav** [comment]
On Firefox: 
screenshot from 2019-02-19 11-21-29

**Comment by caldav** [comment]
:+1:

**Pull request merged**
