### PR TITLE
1596 internet of things robotics

### LINKED ISSUE #1596: /internet-of-things/robotics/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /internet-of-things/robotics to vbt
* chanded the matrix a lot… adding .is-split, .is-trisected and .is-quartered
* blockquote fixed in another PR

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/internet-of-things/robotics)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/7.%20IoT?preview=iot-robotics.png) and [demo](http://www.ubuntu.com-1596-internet-of-things-robotics.demo.haus/internet-of-things/robotics)

## Issue / Card

Fixes #1596

### CODE REVIEW

**Comment by yaili** [comment]
@pmahnke the demo link is linking to this page

**Comment by yaili** [comment]
Design review:
- [ ] From 619px to 449px wide, the some of the logos in the matrix behave differently from others, some get stacked, some get inline - since they are stacked at large screen, it makes sense for all of them to be always stacked - is this possible?

**Comment by yaili** [comment]
- [ ] The matrix doesn't look right - are you using the latest code from @deadlight so that the text can go full width?
- [ ] The images in the "Ubuntu runs on the robotic platforms" matrix are still doing different things in small screens, not all behave the same - is there any way we can redo/design this content so it doesn't look this weird? Maybe cards with logo header + image below?

**Comment by pmahnke** [comment]
@yaili one last try before p-cards

**Comment by pmahnke** [comment]
@yaili removed the p-matrix--content and all seems well!

**Comment by barrymcgee** [comment]
@pmahnke Are you also seeing this at 620px?

screen shot 2017-06-02 at 09 16 59

**Comment by yaili** [comment]
@barrymcgee I don't see it

**Comment by pmahnke** [comment]
@barrymcgee I don't either

image

**Comment by barrymcgee** [comment]
Whaaa? 🤔

screen shot 2017-06-02 at 18 38 37

Can you check please @deadlight?

**Comment by deadlight** [comment]
@barrymcgee I'm getting the bug that you've reported on medium viewports. It works on the demo so there must have been something introduced since the demo was built.

**Pull request merged**
