### PR TITLE
Build OpenStack Queens takeover

### LINKED ISSUE #3196: Build new OpenStack Queens takeover

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Build OpenStack Queens takeover

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Check the takeover matches the design in the issue

## Issue / Card
Fixes #3196

### CODE REVIEW

**Comment by frankiegranato** [comment]
Lets try not to line-break "18.04 LTS" please.

**Comment by anasereijo** [comment]
@steverydz can you make the body copy smaller on mobile? The title gets smaller but seems that the text keeps the desktop size

**Comment by steverydz** [comment]
@anasereijo What size do you want it to be?

**Comment by steverydz** [comment]
@frankiegranato I've stuck a non-breaking space in there now

**Comment by anasereijo** [comment]
@steverydz 16px should be fine, thanks

**Comment by anasereijo** [comment]
@steverydz I don't think the h1 looks ok now. Maybe we can break the text after "and" so it looks the same width as the title.
fyi @frankiegranato

**Comment by frankiegranato** [comment]
Looks ok to me. @anasereijo & @steverydz lets try to get this takeover live asap (It won't be up for more than a week and half).

**Comment by steverydz** [comment]
@anasereijo Font size updated - I've added a couple more non-breaking spaces but remember it's very difficult to guarantee how text will wrap on the web. There are so many variables such as screen width, browser font rendering, user preferences etc.

**Comment by anasereijo** [comment]
@steverydz mobile looks good!
I still think that line of copy looks odd on desktop can you please try to break after "and" of "openstack"?

thanks

**Comment by Caleb-Ellis** [comment]
@anasereijo I agree with @steverydz that we should be careful with overly prescriptive non-breaking spaces. At the iPhone 5 level it looks like this,

screenshot_2

In my opinion only "18.04 LTS" and maaaaybe "OpenStack Queens" should be non-broken.

**Comment by steverydz** [comment]
@anasereijo I've just updated the spaces - should be a new demo any minute now

**Pull request merged**
