### PR TITLE
1597 internet of things thank you

### LINKED ISSUE #1597: /internet-of-things/thank-you/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done
* update /internet-of-things/thank-you to vbt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/internet-of-things/thank-you)
- compare to the [containers design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/11.%20Forms?preview=containers-thank-you.png) and [demo](http://www.ubuntu.com-1597-internet-of-things-thank-you.demo.haus/internet-of-things/thank-you)

## Issue / Card

Fixes #1597

### CODE REVIEW

**Comment by pmahnke** [comment]
NOTE - I based this off the overview page by mistake... do not merge this before that one is merged

**Comment by yaili** [comment]
Design review:
- [ ] Now on live the iot thank you page shows the section's normal breadcrumbs, this demo shows IoT > Thank you, is that change on purpose?

**Comment by pmahnke** [comment]
@yaili it was on purpose, but I can't seem to get it to work on all pages, like contact-us... perhaps I should just remove it? or ask Robin for help?

**Comment by yaili** [comment]
I don't mind either way, as long as it's the same for all thank-yous

**Comment by pmahnke** [comment]
@barrymcgee can you comment on this? if we should use the tertiary nav for contact-us/thank-you pages

**Comment by barrymcgee** [comment]
@pmahnke The breadcrumb trail should show the path you have taken to get to the thank you page so it should also link to the interim page between IOT and /thank-you

**Comment by barrymcgee** [comment]
@pmahnke The `/iot` overview page has now been merged, is this now clear to merge also?

**Comment by yaili** [comment]
@pmahnke @barrymcgee there are no green review labels yet

**Comment by barrymcgee** [comment]
@yaili I'm referring to the "Don't merge" label

**Comment by pmahnke** [comment]
@yaili @barrymcgee I removed the don't merge... I assume the breadcrumb should be

`IoT > Contact us > Thank you`

which is what Robin is working on... not sure if we think this is a blocker here... I think they are generally not correct for Contact us and Thank you pages across the site.

**Comment by yaili** [comment]
@pmahnke I don't think this is a blocker here, as long as we check after @nottrobin has updated breadcrumbs - is there an issue to track that work?

**Comment by nottrobin** [comment]
@yaili, @pmahnke I created #1944 to track the work, and it's ready for review in #1942 and #1943

**Comment by barrymcgee** [comment]
Robin's merged fixes above have now resolved this issue.
screen shot 2017-06-08 at 13 39 13

**Pull request merged**
