### PR TITLE
Update kubernetes managed copy

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Update 'Managed Kubernetes pricing' section of `/kubernetes/managed`

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/managed>
- See that 'Managed Kubernetes pricing' section matches the [copy doc](https://docs.google.com/document/d/15jzhasokjH5Ql9Za56ZxRknXNNhEXYdIFXXtLODGxns/edit#)

## Issue / Card

Fixes [#708](https://github.com/ubuntudesign/web-squad/issues/708)

### CODE REVIEW

**Comment by frankiegranato** [comment]
Looks good but I'm afraid there are a few more small changes need to be captured - refer to  copydoc please @steverydz

**Comment by steverydz** [comment]
@frankiegranato Done

**Comment by frankiegranato** [comment]
- [ ] A few small amends in the copydoc.
- [ ] Remove 'rouge' kubernetes disclaimer
managed kubernetes no disclaimer

**Comment by steverydz** [comment]
@frankiegranato Done

**Pull request merged**
