### PR TITLE
Add login menu

### LINKED ISSUE #3286: beta updates: login menu build
copy doc: https://docs.google.com/document/d/1NIOGd2udYcjQ1xoKGR2UIMruWLXMIRf6R3aZwD7zk2o/edit?ts=5b1560a8

design issue: #3287

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Add login menu to global nav

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/>
- See the login dropdown menu is there and that it matches the design

## Issue / Card

Fixes #3286

### CODE REVIEW

**Comment by steverydz** [comment]
@anthonydillon Fixed by closing the main dropdowns if the global nav is open

**Comment by anasereijo** [comment]
@steverydz 
Desktop is looking good! 👍 

@frankiegranato mobile isn't looking very nice but I think we need to look to the mobile global nav as a whole instead of fixing one section at the time. What do you think? Maybe I can create an issue just for that? Thank you

**Comment by steverydz** [comment]
@anasereijo I agree - a new issue to look at the global nav as a whole would make sense

**Comment by anasereijo** [comment]
@steverydz going to give +1 for desktop... I'm going to create an issue for mobile global nav then.

**Comment by frankiegranato** [comment]
I think the login and signup links are getting a bit lost as white text links. Can we make them all into buttons please? @anasereijo should do another design review when this change has been made.

**Comment by anasereijo** [comment]
FYI I'm triyng a couple of things which I'm discussing with Spencer. I will attach a new solution here once it's signed off by design.

**Comment by anasereijo** [comment]
Hi @steverydz 

- can you please add some extra margin between copy and links? I tried 16px and was looking better
- can you please remove the vertical lines? that's not on my design. see below 

https://user-images.githubusercontent.com/36884067/41462285-45e3a790-708a-11e8-86d8-1deb5a7120d8.jpg

**Comment by steverydz** [comment]
@anasereijo @frankiegranato Changes made

**Comment by anasereijo** [comment]
Hi, @steverydz this is looking good. Just 2 more things and it's ready. 
Make the margins between the line divider the same (check what we have on products) and also remove that extra margin from the bottom of the menu. check my sketching: 
screen shot 2018-06-22 at 14 43 15

**Comment by anasereijo** [comment]
@frankiegranato we added an extra margin between the copy and links. I think this helps to make the links more visible. Let me know your thoughts.

**Pull request merged**
