### PR TITLE
Support thank you page to VBT

### LINKED ISSUE #1588: /support/contact-us/ to VBT

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Updated the thank you page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/support/thank-you](http://0.0.0.0:8001//support/thank-you)
- See it's majesty at all viewports.

## Issue / Card

Fixes #1588

### CODE REVIEW

**Comment by anthonydillon** [comment]
Can't QA locally. Hitting an error when running `./run serve`.

**Comment by yaili** [comment]
@deadlight the demo link isn't working

**Comment by deadlight** [comment]
@yaili: new demo link: http://www.ubuntu.com-1588-support-thank-you.demo.haus/support/thank-you

**Comment by deadlight** [comment]
@barrymcgee can you do the QA that Ant couldn't do, please?

**Pull request merged**
