### PR TITLE
Created /about/packages page

### LINKED ISSUE #3963: New /packages page - Build

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- created new /about/packaging page
- the /about section is very simple, I didn't think it needed design or UX really; however, unless you wanted to add a debian, snap and charm icon?  up to you really @frankiegranato or @anasereijo

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/about/packages](http://0.0.0.0:8001/about/packages)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- compare to the [copy doc](https://docs.google.com/document/d/12PIhHMZZNzwLYCN1sLb1DSX2BejIy6b9-lhupghzNbY/edit?ts=5b7ec54a#heading=h.vyfp6mz8vnc9)

## Issue / Card

Fixes #3963

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @pmahnke I think we can definitely give some love to the About section. But, for now, I suggest keeping the packages page as it is because this needs to be looked/redesigned as whole section. What do you think @frankiegranato ?

**Comment by frankiegranato** [comment]
One small typo. See comment in the copydoc. Aside from that, I think this page is fine. We could spend some time on the 'design' of the page and adding assets but unless someone specifically requests this, I think we should leave this as it is for now. I think that this whole "About" section could use some love.

**Comment by pmahnke** [comment]
@frankiegranato updated

**Comment by frankiegranato** [comment]
Nice

**Pull request merged**
