### PR TITLE
Add ITstrategen case study to /server/livepatch

### LINKED ISSUE #2396: Add case study to /livepatch page
Add Case study to /livepatch page: 
Copydoc: https://docs.google.com/document/d/1ObUSvkDcWOe01pmhh_Aryqxs87D8X2khbJbn3RgqZE0/edit#heading=h.irk5c7cccfsg

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Add ITstrategen case study

### **Requires https://github.com/canonical-websites/www.ubuntu.com/pull/2402 to land first**

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/server/livepatch](http://0.0.0.0:8001/server/livepatch)
- Make sure the page contains the ITstrategen case study as per copy doc

## Issue / Card

Doc: https://docs.google.com/a/canonical.com/document/d/1ObUSvkDcWOe01pmhh_Aryqxs87D8X2khbJbn3RgqZE0/edit?disco=AAAABa0kIas

Fixes #2396

### CODE REVIEW

**Comment by frankiegranato** [comment]
@grahambancroft I'm seeing a "TemplateDoesNotExist" message when I navigate to the /livepatch page  via this link: http://www.ubuntu.com-pr-2403.run.demo.haus/server/livepatch 
:-(

**Comment by grahambancroft** [comment]
@frankiegranato I've merged in #2402 now, so this is ready for review again

**Comment by michaelb17** [comment]
@grahambancroft After looking closely I've realised the asset used is a PNG. For clarity and crispness can we make it an SVG. Ill locate and provide the asset.

**Comment by grahambancroft** [comment]
@michaelb17 Done

**Pull request merged**
