### PR TITLE
1592 internet of things contact us

### LINKED ISSUE #1592: /internet-of-things/contact-us/ to VBT

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* update /internet-of-things/contact-us to vbt

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/internet-of-things/contact-us)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/11.%20Forms?preview=iot-contact.png) and the [demo](http://www.ubuntu.com-1592-internet-of-things-contact-us.demo.haus/internet-of-things/contact-us)

## Issue / Card

Fixes #1592

### CODE REVIEW

**Comment by yaili** [comment]
- [ ] The button doesn't look like it has the correct padding from Vanilla - this has happened before with a page @barrymcgee worked on, I think - but I can't check right now because Vanilla docs aren't working for me, can you confirm?

**Comment by pmahnke** [comment]
@yaili I am having issues with demo.haus and v.io docs as well, but it is using .p-button--brand

look tomorrow

**Comment by pmahnke** [comment]
@yaili I think it is correct (as discussed)

**Comment by barrymcgee** [comment]
@pmahnke Fix conflicts and this is good to merge.

**Pull request merged**
