### PR TITLE
699 ai features

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Updated `/ai/features` as per the copy doc

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: <http://0.0.0.0:8001/ai/features>
- See that page matches the [copy doc](https://docs.google.com/document/d/1DT5nCRSJH-OkvDmlyKh6vVhofeHPHZJHTTBDNu44wCY/edit#)

## Issue / Card

Fixes [#699](https://github.com/ubuntudesign/web-squad/issues/699)

### CODE REVIEW

**Comment by frankiegranato** [comment]
The text above the final cta has changed :-)

**Comment by steverydz** [comment]
@frankiegranato Done

**Comment by anthonydillon** [comment]
@steverydz did you mean to merge this into master?

**Comment by steverydz** [comment]
@anthonydillon No, updated the base

**Comment by shivjoshi1996** [comment]
@steverydz Found another little copy difference, have a look when you get a sec.

**Comment by steverydz** [comment]
@shivjoshi1996 Fixed

**Comment by frankiegranato** [comment]
Can you add a heading to the footer as per the doc. Sorry!

**Comment by steverydz** [comment]
@frankiegranato Done

**Pull request merged**
