### PR TITLE
Update community.ubuntu.com links and redirects

### LINKED ISSUE #2265: Link to community site now broken
https://www.ubuntu.com/support/community-support contains a link to "Get free Community Support" which links to https://community.ubuntu.com/help-information/ which has moved to discourse, the new page should probably be:- https://community.ubuntu.com/t/supporting-users/20

---
*Reported from: https://www.ubuntu.com/support/community-support*

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* the new community site requires moving all deep links to the top level of the domain

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at:
  - [about](http://0.0.0.0:8001/about)
  - [server](http://0.0.0.0:8001/server)
  - [comm support](http://0.0.0.0:8001/support/community-support)
  - [contrib thank-you](http://0.0.0.0:8001/legal/contributors/thank-you)

etc…

## Issue / Card

Fixes #2265

### CODE REVIEW

**Comment by anthonydillon** [comment]
Looks like there are still broken links in the tests.

**Comment by anthonydillon** [comment]
Merry also be worth referencing https://github.com/canonical-websites/www.ubuntu.com/issues/2265

**Comment by pmahnke** [comment]
@anthonydillon fixed a bunch more

**Comment by pmahnke** [comment]
@anthonydillon what do you mean by 'Merry also be worth referencing #2265' I already did a Fixes and zen hub link to that issue

**Comment by anthonydillon** [comment]
@pmahnke sorry I meant that there was a comment in the issue saying there are some replicated pages in the new community site which we can point at. I have updated this PR with the links I could find.

**Pull request merged**
