### PR TITLE
Add LTS EOL dates

### LINKED ISSUE #2401: Display LTS dates
Please add the support window dates to the relevant download pages on your website.  At https://www.ubuntu.com/download/desktop it is noted that 16.04 is an LTS release and has a 5-year support window, but does not say when that window starts or ends!  Furthermore, there is a link to the release notes.  Surely that info will be there... nope.  Maybe the change summary... nope.  Is there anywhere on your website that immediately shows the support dates?  Not that I could easily find.  

I had to google it to get to find a wiki page with the info.  It is still incomplete, however.  There are no end support dates for some releases at https://wiki.ubuntu.com/Releases.  All relevant info for the release should be on the download page.

Please, understand your audience.  We want simple, clear, obvious relevant info.  These pages are as much info for technical users as is marketing, or rather, it should be.

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

- Add 17.10 EOL date as variable
- Update /download/desktop as per copy doc

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at:
  - [http://0.0.0.0:8001/desktop/developers](http://0.0.0.0:8001/desktop/developers)
  - [http://0.0.0.0:8001/server](http://0.0.0.0:8001/server)
  - [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
  - [http://0.0.0.0:8001/download/desktop](http://0.0.0.0:8001/download/desktop)
  - [http://0.0.0.0:8001/cloud/public-cloud](http://0.0.0.0:8001/cloud/public-cloud)
  - [http://0.0.0.0:8001/download/server](http://0.0.0.0:8001/download/server)
  - [http://0.0.0.0:8001/download/server/power8](http://0.0.0.0:8001/download/server/power8)
- Make sure it looks okay
- Check change made to /download/desktop reflect changes in the copy doc

## Issue / Card

Fixes #2401 
Doc: https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#heading=h.jvy8qhtxsktf

### CODE REVIEW

**Comment by anthonydillon** [comment]
Code looks ok :+1:

**Comment by grahambancroft** [comment]
I've added code and QA labels back as the code has changed significantly

**Comment by grahambancroft** [comment]
@frankiegranato approves

**Comment by anthonydillon** [comment]
QA:
- Looked through the changes pages
- Saw nothing out of place.

**Pull request merged**
