### PR TITLE
Move release EOL page to /about/release-cycle and update copy

### LINKED ISSUE #3842: Please move  /info/release-end-of-life to /about/release-cycle
per kiko and mark

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Moved /info/release-end-of-life page to /about/release-cycle
- Updated copy according to the [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
- Added redirects to new page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Check that the page content matches the [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
- **Note that the /about/kernel page has not been finalised yet, so for now the kernel section has a link to wiki.ubuntu.com/Kernel**
- Go to http://0.0.0.0:8001/info/release-end-of-life and check that it redirects to http://0.0.0.0:8001/about/release-cycle

## Issue / Card

Fixes #3842

### CODE REVIEW

**Comment by anasereijo** [comment]
@Caleb-Ellis can you please check mobile tables?

Everything looks fine although I think it looks very copy heavy but I guess we can't do anything about that.

**Comment by frankiegranato** [comment]
One small update to content. See copydoc. (aside from this, it would be a +1 from me)

**Comment by anthonydillon** [comment]
@anasereijo the mobile tables are an issue in Vanilla

**Comment by Caleb-Ellis** [comment]
UX + 1 from @frankiegranato after discussion, added an issue #3877 regarding release chart

**Pull request merged**
