### PR TITLE
Add interactive forms to the bootstack section

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add interactive forms to the bootstack section. Set up the form on the page. Added some styling to align Other inputs.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Go to /openstack/managed
- Click the contact button
- Check that the contact form matches the [copy docs](https://docs.google.com/document/d/14dJOH-eHQTQcw-eA7dxLaYYqxZofcumVpW4A7ShzB-s/edit#heading=h.tk4y6g6el1tm)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4591

### CODE REVIEW

**Comment by anasereijo** [comment]
Hi @anthonydillon, only 1 suggestion and it's ready to go:

- [ ] remove extra space above Other inputs:

bootstack managed openstack on ubuntu openstack ubuntu

**Comment by anthonydillon** [comment]
@anasereijo if you see the copy doc. The space was requested.

**Comment by anasereijo** [comment]
@anthonydillon keep it as per copydoc for now and I'll show it on design review meeting and see if there's anything we can do in the future to improve it. thank you

**Comment by caldav** [comment]
@ant, why is that include on /openstack/training while QA steps mention /openstack/managed? I'm wondering, as we have 2 includes on the /openstack/training page, one that looks right and points at an openstack training formid in Marketo, and this one. I'm wondering if it was a mistake in this PR or if it has a purpose.

**Pull request merged**
