### PR TITLE
2730: Update /download/cloud page

### LINKED ISSUE #2730: Build /download/cloud page
## Summary

we are moving the existing pages to /openstack

here is the new page's [copy doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit#)

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Built new /download/cloud page according to [copydoc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit#)

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/cloud
- Check that the page matches the [copydoc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit#)

## Issue / Card

Fixes #2730

### CODE REVIEW

**Comment by frankiegranato** [comment]
I love the use of the cards, but some of the logos look huge compared to others. Can we get them to look more consistent? Nb @kwm14

**Comment by frankiegranato** [comment]
@Caleb-Ellis see a few other notes in the copydoc.

**Comment by spencerbygraves** [comment]
If we start to use these cards in more places, I think the link text at the bottom should be 16px. 14px was fine when it was only a topic label in resources. I also think we could remove the margin top.

Can we also make the amazon logo smaller, I set it to max-height: 4rem;

Thanks

Here's an example of the changes:
image

**Comment by frankiegranato** [comment]
@Caleb-Ellis I'm sorry - I've messed up the contextual footer. Can you please replace the content in the middle column with the content I've specified in the copydoc?

**Comment by pmahnke** [comment]
@spencerbygraves @Caleb-Ellis @kwm14  @frankiegranato I worry that we are using these cards too much

I think the plain Vanilla ones look better frankly for this

image
image
(I added some min-height to the bottom one)

**Comment by pmahnke** [comment]
@Caleb-Ellis also, it still has the build and try links in the nav, unless you are moving these in another PR

**Comment by spencerbygraves** [comment]
@pmahnke thanks for pointing this out, you're right that we shouldn't overuse them. As we discussed just now, let's keep this card style for Resources and Insights. @frankiegranato is that ok with you?

**Comment by Caleb-Ellis** [comment]
@pmahnke @spencerbygraves I've updated it now so that the top three cards are highlighted and the bottom three are just normal cards (all Vanilla). I've also removed the openstack stuff from the nav (and I'll put them in the right place with the openstack PRs)

**Comment by pmahnke** [comment]
@Caleb-Ellis last link should be to /support and the title needs a 'the'

Ubuntu Advantage for **the** public cloud
Flexible Ubuntu Virtual Guest options designed for virtualised workloads on Ubuntu-certified public clouds.
[Get support >](/support)

**Pull request merged**
