### PR TITLE
Added canonical-global-nav as a dependency

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Added canonical-global-nav as a dependency and removed all the old global navigation code.

## QA
- Pull branch and run `./run`
- Go to http://0.0.0.0:8001/
- See that the global navigation is there and works
- Check small screens

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/1725 https://github.com/canonical-websites/www.ubuntu.com/issues/1687

Demo: http://www.ubuntu.com-global-nav.demo.haus

### CODE REVIEW

**Comment by barrymcgee** [comment]
@anthonydillon Sass has failed to run.

**Comment by barrymcgee** [comment]
@anthonydillon Still getting error running Sass

screen shot 2017-05-08 at 13 48 54

**Comment by anthonydillon** [comment]
@nottrobin looks like `.run` on this project does not install bower dependencies?

**Comment by anthonydillon** [comment]
@barrymcgee do you mind trying it now. CI is still failing but installing bower stuff locally for me.

**Comment by anthonydillon** [comment]
@yaili would you mind taking a look at the demo for this please? http://www.ubuntu.com-global-nav.demo.haus

**Comment by yaili** [comment]
- It shouldn't be dark in small screens. Can we keep same colour across breakpoints? 
- The links should align left with the external icon

**Comment by anthonydillon** [comment]
Thanks, @yaili.

Picking up the changes in the global-nav project https://github.com/canonical-webteam/global-nav/issues/26.

**Comment by anthonydillon** [comment]
Blocked on this PR: https://github.com/canonical-webteam/global-nav/pull/27

**Comment by barrymcgee** [comment]
This now unblocked as https://github.com/canonical-webteam/global-nav/pull/27 is merged.

**Pull request merged**
