### PR TITLE
[UA-I] updates for /support/plans-and-pricing page 

### LINKED ISSUE #4873: [UA4I] update /support/plans-and-pricing
[copy doc](https://docs.google.com/document/d/1FS1slJOfWXLmPob1eXrQ32DU4s6WP4oyGoT3t5E4W8Y/edit#heading=h.l83dv5879ajz)

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

[List of work items including drive-bys]

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Compare to the [copy doc](https://docs.google.com/document/d/1FS1slJOfWXLmPob1eXrQ32DU4s6WP4oyGoT3t5E4W8Y/edit#)

## Issue / Card

Fixes #4873

### CODE REVIEW

**Comment by anasereijo** [comment]
Amendments:

- Amend `headings` hierarchy (@Khutch25 amended the copy doc)
- Some "get in touch" buttons are `neutral` and others are `positive`. Can we make this consistent across the page? I suggest the first button on each section to be `positive` and the others `neutral`. 

Plans and pricing   Support   Ubuntu

Plans and pricing   Support   Ubuntu (1)


Plans and pricing   Support   Ubuntu (2)


Plans and pricing   Support   Ubuntu (3)


Plans and pricing   Support   Ubuntu (4)

Plans and pricing   Support   Ubuntu (5)

Plans and pricing   Support   Ubuntu (6)

Plans and pricing   Support   Ubuntu (7)

**Comment by pmahnke** [comment]
@anasereijo ready for review... and don't forget to think about highlighting a row of support hours

**Comment by anasereijo** [comment]
@pmahnke 

- to highlight a row we should make the text `font-weight: 400;`
- can we have buttons `positive` after an `h2` and all the other ones `neutral`? This will make it more consistent as at the moment some of them are neutral and others positive without any specific reason.

**Comment by anasereijo** [comment]
👍 looking good!

just noticed that the asterisks on Add-ons section are anchor links and but they all link to the same section. I think we should remove the links.

Screenshot 2019-03-26 at 14 21 14

**Comment by pmahnke** [comment]
@anasereijo 	the * links are all over the page... you want me to remove them all?

**Pull request merged**
