### PR TITLE
Create the OpenStack install page

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Create the OpenStack install page and removed the developer page.

## QA
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/install](http://0.0.0.0:8001/openstack/install)
- Check the page matches the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)

## Issue / Card
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3288

### CODE REVIEW

**Comment by steverydz** [comment]
Just one thing:

`sudo maas init` in Step 3: Install MAAS should be `sudo maas createadmin` according to the copy doc.

**Comment by anthonydillon** [comment]
@steverydz I have asked in the copydoc to change this. I believe `init` is the correct command.

**Comment by frankiegranato** [comment]
I can not answer the tecnical questions that need resolving in this copydoc, so I have asked Tim Van Steenburgh and Adam Stokes to review this page. I'm going to mark this page as blocked until they come back to us. 
--


 and Adam Stokes

**Comment by anasereijo** [comment]
@anthonydillon 

some amends on the jpg below

screencapture-ubuntu-pr-3459-run-demo-haus-openstack-install-2018-06-27-09_50_33

**Comment by anthonydillon** [comment]
@anasereijo done your suggested changes. The stepped alignment will be in place from the other PR you mentioned it so you can ignore it here.

**Comment by anasereijo** [comment]
@anthonydillon looking good! I'm ignoring the stepped alignment as you said, so giving it +1

**Comment by frankiegranato** [comment]
screen shot 2018-06-27 at 15 39 12

- [ ] 'Install' appears twice.

**Comment by frankiegranato** [comment]
I notice we still need some padding inbetween the steps. Can we see this happen?

**Comment by frankiegranato** [comment]
You need to add a new image in step 10.
Plus a few other small changes. Please see comments in the doc and be EXTRA diligent about capturing them all. Mark is very interested in this page.

**Comment by anthonydillon** [comment]
@frankiegranato updated based on your comments.

**Pull request merged**
